// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4adfa70d4f302ff49ce0585fb7c4fa1aa96832d1b3e0e88cc6da1ac127acd0ef
// To regenerate: alef generate
// To verify freshness: alef verify

package htmltomarkdown

import "embed"

// This file ensures that the C header is included when this module is vendored.
// The //go:embed directive tells Go to include the include/ directory when
// running `go mod vendor`. Native libraries are intentionally NOT embedded here
// — they are too large to commit and are downloaded at consume-time by
// `cmd/setup` into a per-user cache instead (see cmd/setup/main.go).
//
// Unlike the old vendor-only stub, this file is a real compiled member of the
// package: dropping the `//go:build ignore` guard is what makes `go mod vendor`
// (which only follows imports reachable from compiled files) include it.

//go:embed include/*
var _ embed.FS
