// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d37e6bcb9153258139a8ba9e40d15bb23486c494563746b8815358d3bb7ff1b1
// To regenerate: alef generate
// To verify freshness: alef verify

module github.com/xberg-io/html-to-markdown/packages/go/v3

go 1.26
