// Code generated by alef — DO NOT EDIT.
// alef:hash:f6e4b500605b37962e388c0099ca5f8f2e0c744de3a367a7b33edce8afd7ce6d
package htmltomarkdown

// RequireNativeSetup_3_11_3 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_11_3 = "3.11.3"
