// Code generated by alef — DO NOT EDIT.
// alef:hash:be3df46a4538bc5f34395a2a6a0dc337caa084181b33c063a791d0f918d4da12
package htmltomarkdown

// RequireNativeSetup_3_11_6 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_12_0 = "3.12.0"
