// Code generated by alef — DO NOT EDIT.
// alef:hash:6372c8d306a4daf58b122425dcd0b821c5a023c8dd011af915a54dcd39f3b1c8
package htmltomarkdown

// RequireNativeSetup_3_11_4 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_11_5 = "3.11.5"
