# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22cc656495ad800c6db992f60fdc222581bfe33b5339d6487ae2f9aa4575cc1d
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.11.3"
end
