# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fcc2f2593bb790d684484c0c5716feaee2e66abbffbe8e64f0a07b2261cffd40
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.11.6"
end
