# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f0f83a7f0ec95e9fa6c14023596214a907e0d582a13cd8979fb46cd5f72db15c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.10.2"
end
