// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cfe52c3f18c7fc0440800f6aab14ef33ae5c1c287acce17ebcd0a5c81334c6fe
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
