// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:340defd19ee70e90a7b00a2f444b1eebfbbef5460ccfe3950039dfce2ad4ccb0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
