// Generated by alef. Do not edit by hand.
// alef:hash:222a2cefaab03c63c94d571e479819484f72479ca18802dce125eb94a4a98bba

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-android-e2e"
