// Generated by alef. Do not edit by hand.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-android-e2e"
