<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e7e67ddf9c01abb736db185dd5fcf8218489c2d82f2e9856d090db92da92c66f
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);

// Verify the extension is loaded.
if (!extension_loaded('html_to_markdown')) {
    fwrite(STDERR, "FAIL: html_to_markdown extension is not loaded\n");
    exit(1);
}

// Verify the configured facade method exists.
if (!class_exists('HtmlToMarkdown\HtmlToMarkdownApi')) {
    fwrite(STDERR, "FAIL: class HtmlToMarkdown\HtmlToMarkdownApi not found\n");
    exit(1);
}
if (!method_exists('HtmlToMarkdown\HtmlToMarkdownApi', 'convert')) {
    fwrite(STDERR, "FAIL: HtmlToMarkdown\HtmlToMarkdownApi::convert() not found\n");
    exit(1);
}

// Smoke-test the configured facade method.
$result = HtmlToMarkdown\HtmlToMarkdownApi::convert('smoke test');

if ($result === null) {
    fwrite(STDERR, "FAIL: expected non-null result\n");
    exit(1);
}

echo "PASS: HtmlToMarkdown\HtmlToMarkdownApi::convert() returned a non-null result\n";
exit(0);
