<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9e875201aaa1463c15e0a241122082d3c23e810863377fbf0f9aab8c635da0e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

// Verify the extension is loaded.
if (!extension_loaded('html_to_markdown')) {
    fwrite(STDERR, "FAIL: html_to_markdown extension is not loaded\n");
    exit(1);
}

// Verify the configured function exists.
if (!function_exists('html_to_markdown_convert')) {
    fwrite(STDERR, "FAIL: html_to_markdown_convert() not found\n");
    exit(1);
}

// Smoke-test the configured function.
$result = html_to_markdown_convert('smoke test');

if ($result === null) {
    fwrite(STDERR, "FAIL: expected non-null result\n");
    exit(1);
}

echo "PASS: html_to_markdown_convert() returned a non-null result\n";
exit(0);
