# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f15fb9a6ca964bfef00617cc14d7c0666ff49afcbd129289d079595c245029c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: smoke
defmodule E2e.SmokeTest do
  use ExUnit.Case, async: false

  describe "smoke_empty_string" do
    test "smoke_empty_string" do
      {:ok, result} = HtmlToMarkdown.convert("")
      assert String.trim(result.content) == ""
    end
  end

  describe "smoke_simple_heading" do
    test "smoke_simple_heading" do
      {:ok, result} = HtmlToMarkdown.convert("<h1>Title</h1>")
      assert String.contains?(to_string(result.content), "\# Title")
    end
  end

  describe "smoke_simple_paragraph" do
    test "smoke_simple_paragraph" do
      {:ok, result} = HtmlToMarkdown.convert("<p>Hello World</p>")
      assert String.trim(result.content) == "Hello World"
      assert result.content != ""
    end
  end
end
