# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49ec1ff764bd8684b6ef8834f027a08a091379b0b3b15b747753837b86f797a9
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: smoke
defmodule E2e.SmokeTest do
  use ExUnit.Case, async: false

  describe "smoke_empty_string" do
    test "smoke_empty_string" do
      {:ok, result} = HtmlToMarkdown.convert("")
      assert result.content == ""
    end
  end

  describe "smoke_simple_heading" do
    test "smoke_simple_heading" do
      {:ok, result} = HtmlToMarkdown.convert("<h1>Title</h1>")
      assert String.contains?(to_string(result.content), "\# Title")
    end
  end

  describe "smoke_simple_paragraph" do
    test "smoke_simple_paragraph" do
      {:ok, result} = HtmlToMarkdown.convert("<p>Hello World</p>")
      assert result.content == "Hello World"
      assert result.content not in [nil, "", [], %{}]
    end
  end
end
