// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using HtmlToMarkdown;
using static HtmlToMarkdown.HtmlToMarkdownConverter;

namespace HtmlToMarkdown
{
    /// <summary>E2e tests for category: smoke.</summary>
    public class SmokeTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_SmokeEmptyString()
        {
            // Empty string produces empty output
            var result = HtmlToMarkdownConverter.Convert("", new ConversionOptions());
    Assert.Equal("", result.Content!.Trim());

        }

        [Fact]
        public void Test_SmokeSimpleHeading()
        {
            // H1 heading converts to ATX markdown
            var result = HtmlToMarkdownConverter.Convert("<h1>Title</h1>", new ConversionOptions());
    Assert.Contains("# title", result.Content.ToString().ToLower());

        }

        [Fact]
        public void Test_SmokeSimpleParagraph()
        {
            // Simple paragraph converts correctly
            var result = HtmlToMarkdownConverter.Convert("<p>Hello World</p>", new ConversionOptions());
    Assert.Equal("Hello World", result.Content!.Trim());
    Assert.False(string.IsNullOrEmpty(result.Content?.ToString()));

        }


    }
}
