<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94dd1be9921f0c99181696abdb7a25b59df4f9229ed5f05876faf9831bbba0f5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

namespace HtmlToMarkdown\E2e;

use HtmlToMarkdown\ConversionOptions;
use HtmlToMarkdown\HtmlToMarkdown;
use PHPUnit\Framework\TestCase;

/** E2e tests for category: smoke. */
final class SmokeTest extends TestCase
{
    /** Empty string produces empty output */
    public function test_smoke_empty_string(): void
    {
        $result = HtmlToMarkdown::convert('');

        $this->assertEquals('', trim($result->content ?? null));
    }

    /** H1 heading converts to ATX markdown */
    public function test_smoke_simple_heading(): void
    {
        $result = HtmlToMarkdown::convert('<h1>Title</h1>');

        $this->assertStringContainsString('# Title', $result->content ?? null);
    }

    /** Simple paragraph converts correctly */
    public function test_smoke_simple_paragraph(): void
    {
        $result = HtmlToMarkdown::convert('<p>Hello World</p>');

        $this->assertEquals('Hello World', trim($result->content ?? null));
        $this->assertNotEmpty($result->content ?? null);
    }
}
