// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f36a81b748fd785864972181d5ea68b16baba3107ae28e57ac973611d4d95860
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.android.e2e

import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

class ExcludedBindingsTest {
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_element_with_nesting() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_deeply_nested_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_element_end_modification() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_element_start_skip_entire_subtree() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_unknown_tag_preservation() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_audio_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_audio_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_button_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_button_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_continue_default() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_blockquote() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_emphasis() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_heading() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_image() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_link_format() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_link_static() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_custom_output() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_definition_list_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_definition_list_custom_format() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_definition_list_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_details_summary_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_details_summary_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_figure_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_figure_custom_wrap() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_figure_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_form_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_form_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_heading_bare_string_preserves_case() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_horizontal_rule_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_horizontal_rule_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_iframe_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_iframe_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_image_bare_string_preserves_case() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_input_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_input_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_line_break_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_line_break_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_link_bare_string_preserves_case() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_mark_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_mark_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_preserve_html() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_skip_code_blocks() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_skip_heading() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_skip_images() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_skip_links() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_skip_strong() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_subscript_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_subscript_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_superscript_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_superscript_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_underline_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_underline_skip() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_video_custom() {}
    @Test
    @Disabled("visitor is excluded by crates.kotlin_android.exclude_functions")
    fun visitor_video_skip() {}
}
