// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fd6bc09acae5b7fad5bd1115f08cfe254c3c08f3d3fab8964253cba0a5729c56
// To regenerate: alef generate
// To verify freshness: alef verify
//! E2e tests for category: smoke

use html_to_markdown_rs::ConversionOptions;
use html_to_markdown_rs::convert;

#[test]
fn test_smoke_empty_string() {
    // Empty string produces empty output
    let html = r#""#;
    let options: ConversionOptions = Default::default();
    let result = convert(html, Some(options.clone())).expect("call failed");
    let _content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert_eq!(_content.to_string(), r#""#, "equals assertion failed");
}

#[test]
fn test_smoke_simple_heading() {
    // H1 heading converts to ATX markdown
    let html = r#"<h1>Title</h1>"#;
    let options: ConversionOptions = Default::default();
    let result = convert(html, Some(options.clone())).expect("call failed");
    let _content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert!(_content.contains(r#"# Title"#), "expected to contain: {}", r#"# Title"#);
}

#[test]
fn test_smoke_simple_paragraph() {
    // Simple paragraph converts correctly
    let html = r#"<p>Hello World</p>"#;
    let options: ConversionOptions = Default::default();
    let result = convert(html, Some(options.clone())).expect("call failed");
    let _content = result.content.as_ref().map(|v| v.to_string()).unwrap_or_default();
    assert_eq!(_content.to_string(), r#"Hello World"#, "equals assertion failed");
    assert!(!_content.is_empty(), "expected non-empty value");
}
