<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:05d2d11740607b326b2af5730c7e2eeebbe6f8a2d80f427aedd7ff0af5ae1609
// To regenerate: alef generate
// To verify freshness: alef verify


declare(strict_types=1);

namespace HtmlToMarkdown\E2e;

use PHPUnit\Framework\TestCase;
use HtmlToMarkdown\HtmlToMarkdown;
use HtmlToMarkdown\ConversionOptions;

/** E2e tests for category: smoke. */
final class SmokeTest extends TestCase
{


    /** Empty string produces empty output */
    public function test_smoke_empty_string(): void
    {
        $result = HtmlToMarkdown::convert("");

            $this->assertEquals("", ($result->content ?? null));


    }


    /** H1 heading converts to ATX markdown */
    public function test_smoke_simple_heading(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Title</h1>");

            $this->assertStringContainsString("# Title", ($result->content ?? null));


    }


    /** Simple paragraph converts correctly */
    public function test_smoke_simple_paragraph(): void
    {
        $result = HtmlToMarkdown::convert("<p>Hello World</p>");

            $this->assertEquals("Hello World", ($result->content ?? null));
            $this->assertNotSame('', ($result->content ?? null) ?? '', 'expected non-empty value');


    }

}
