<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:81ce7477531ed66bf6f1d4d10108545f47918fc8308edb1bf5b2a46e5280813c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace HtmlToMarkdown\E2e;

use PHPUnit\Framework\TestCase;
use HtmlToMarkdown\HtmlToMarkdown;
use HtmlToMarkdown\ConversionOptions;

/** E2e tests for category: smoke. */
final class SmokeTest extends TestCase
{

    /** Empty string produces empty output */
    public function test_smoke_empty_string(): void
    {
        $result = HtmlToMarkdown::convert("");

            $this->assertEquals("", trim(($result->content ?? null)));


    }


    /** H1 heading converts to ATX markdown */
    public function test_smoke_simple_heading(): void
    {
        $result = HtmlToMarkdown::convert("<h1>Title</h1>");

            $this->assertStringContainsString("# Title", ($result->content ?? null));


    }


    /** Simple paragraph converts correctly */
    public function test_smoke_simple_paragraph(): void
    {
        $result = HtmlToMarkdown::convert("<p>Hello World</p>");

            $this->assertEquals("Hello World", trim(($result->content ?? null)));
            $this->assertNotEmpty(($result->content ?? null));


    }

}
