# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ef4b1f2f47b13ad4d5aea6f9d22b84a1f21316a769c44db29d52abe3c632347
# To regenerate: alef generate
# To verify freshness: alef verify
# E2e tests for category: smoke

test_that("smoke_empty_string: Empty string produces empty output", {
  result <- convert(html = "", options = ConversionOptions$default())
  expect_equal(result$content, "")
})

test_that("smoke_simple_heading: H1 heading converts to ATX markdown", {
  result <- convert(html = "<h1>Title</h1>", options = ConversionOptions$default())
  expect_true(any(grepl("# Title", result$content, fixed = TRUE)))
})

test_that("smoke_simple_paragraph: Simple paragraph converts correctly", {
  result <- convert(html = "<p>Hello World</p>", options = ConversionOptions$default())
  expect_equal(result$content, "Hello World")
  expect_true(if (is.character(result$content)) length(result$content) > 0 && any(nchar(result$content) > 0) else length(result$content) > 0)
})
