// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:35dee878e342ec8714cea16517ab6013dc4e83ee1cf837167b8c0196bc63d192
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
