// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27ed32559583cdb3be2dc1f2273cf26193710e8e23c5a131df287eaa0fe16e3f
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
