// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b1080479a52ee4275a78d04cd7ed092a7678e92a8722a57feb81da23647b688
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
