# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:707ec1953a6a9dc02c00f630a56b5582b5db3d746a987e6b94d42755c12c16a6
# To regenerate: alef generate
# To verify freshness: alef verify
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
