# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
