# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aff1fb6a41198ba936446c1d39dc1abf10cc3a3e9adfd5d483552b6c011e752f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
library(testthat)
library(htmltomarkdown)

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
