// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba7eea2a8b48fa8c24b31e3b4c2b24a68e786950190c0c908d838ea4bc1f9995
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 60000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
