// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:83c6a48b12ba43bd827a5ae6c0f2100e8b4f88c9dcfa9a047144273a59f4632a
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 60000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
