// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76fade10303923f3f2d8c3d07f8f09a24446cd858900851545ad413f271b7c74
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 60000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
