// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.Optional;

/**
 * The type of an inline text annotation.
 *
 * Uses internally tagged representation ({@code "annotation_type": "bold"}) for
 * JSON serialization.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "annotation_type",
              visible = false)
@JsonSubTypes({
  @JsonSubTypes.Type(value = AnnotationKind.Bold.class, name = "bold")
  , @JsonSubTypes.Type(value = AnnotationKind.Italic.class, name = "italic"),
      @JsonSubTypes.Type(value = AnnotationKind.Underline.class,
                         name = "underline"),
      @JsonSubTypes.Type(value = AnnotationKind.Strikethrough.class,
                         name = "strikethrough"),
      @JsonSubTypes.Type(value = AnnotationKind.Code.class, name = "code"),
      @JsonSubTypes.Type(value = AnnotationKind.Subscript.class,
                         name = "subscript"),
      @JsonSubTypes.Type(value = AnnotationKind.Superscript.class,
                         name = "superscript"),
      @JsonSubTypes.Type(value = AnnotationKind.Highlight.class,
                         name = "highlight"),
      @JsonSubTypes.Type(value = AnnotationKind.Link.class, name = "link")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface AnnotationKind {

  /**
   * Bold / strong emphasis.
   */
  record Bold() implements AnnotationKind {}

  /**
   * Italic / emphasis.
   */
  record Italic() implements AnnotationKind {}

  /**
   * Underline.
   */
  record Underline() implements AnnotationKind {}

  /**
   * Strikethrough / deleted text.
   */
  record Strikethrough() implements AnnotationKind {}

  /**
   * Inline code.
   */
  record Code() implements AnnotationKind {}

  /**
   * Subscript text.
   */
  record Subscript() implements AnnotationKind {}

  /**
   * Superscript text.
   */
  record Superscript() implements AnnotationKind {}

  /**
   * Highlighted / marked text.
   */
  record Highlight() implements AnnotationKind {}

  /**
   * A hyperlink sourced from an {@code &lt;a href="..."&gt;} element.
   */
  record Link(@JsonProperty("url") String url,
              @JsonProperty("title") Optional<String> title)
      implements AnnotationKind {}
}
