// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e9679ed8a98f2fc8ea25e322e7d41ac8d4922e7426d5e0a5c09d9246b727d227
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.JsonSerializer;

/**
 * Serialises {@code byte[]} as a JSON array of integers.
 *
 * <p>Jackson's default serialiser encodes {@code byte[]} as a base64 string, but
 * Rust's {@code serde} for {@code Vec<u8>} expects {@code [72, 101, 108, ...]}.
 * Annotate any {@code byte[]} field sent to the FFI layer with
 * {@code @JsonSerialize(using = ByteArraySerializer.class)}.
 */
@SuppressWarnings("PMD")
public class ByteArraySerializer extends JsonSerializer<byte[]> {

    @Override
    public void serialize(final byte[] value, final JsonGenerator gen,
            final SerializerProvider provider) throws java.io.IOException {
        gen.writeStartArray();
        for (byte b : value) {
            gen.writeNumber(b & 0xFF);
        }
        gen.writeEndArray();
    }
}
