// DO NOT EDIT - auto-generated by alef
// alef:hash:c9f0d87b0d52e348a025fcf6e0fa4e55f166e96a105f82c2eb4003a9c287428f
package io.xberg.htmltomarkdown;

/**
 * Invalid configuration
 */
public class ConfigErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConfigErrorException with the given message. */
  public ConfigErrorException(final String message) {
    super(message);
  }

  /** Creates a new ConfigErrorException with the given message and cause. */
  public ConfigErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
