// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ebc912aed2caee505f437972782d887f5d2a45905d69117da3e8ee08420092f2
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

/** Exception thrown when an FFI value conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends HtmlToMarkdownRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(1, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
