// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6654cad8fd4d8fa0914ec17dcca82229240e55713417730e9b5152b87298c4aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends HtmlToMarkdownRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ConversionErrorException. */
  public ConversionErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new ConversionErrorException with a cause. */
  public ConversionErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
