// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:55f3333ea945315ef1b9f7f825a990561757f33449338c231c3085499dbd9fac
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

/** Exception thrown when the Rust core reports an unknown error. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class CoreErrorException extends HtmlToMarkdownRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CoreErrorException. */
  public CoreErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new CoreErrorException with a cause. */
  public CoreErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
