// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ab632decc7f3db663597e33072a9c38e15468dacb8d1fc9ed8001db565106ed9
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

/** Exception thrown when the Rust core reports an unknown error. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class CoreErrorException extends HtmlToMarkdownRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CoreErrorException. */
  public CoreErrorException(final String message) {
    super(2, message);
  }

  /** Creates a new CoreErrorException with a cause. */
  public CoreErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
