// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0f83a7f0ec95e9fa6c14023596214a907e0d582a13cd8979fb46cd5f72db15c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Heading style options for Markdown output.
 *
 * Controls how headings (h1-h6) are rendered in the output Markdown.
 */
@SuppressWarnings("PMD")
public enum HeadingStyle {
  /**
   * Underlined style (=== for h1, --- for h2).
   */
  Underlined("underlined"),
  /**
   * ATX style (# for h1, ## for h2, etc.). Default.
   */
  Atx("atx"),
  /**
   * ATX closed style (# title #, with closing hashes).
   */
  AtxClosed("atxclosed");

  /** The string value. */
  private final String value;

  HeadingStyle(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static HeadingStyle fromValue(final String value) {
    for (HeadingStyle e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown HeadingStyle value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
