// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0f83a7f0ec95e9fa6c14023596214a907e0d582a13cd8979fb46cd5f72db15c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Highlight rendering style for {@code &lt;mark&gt;} elements.
 *
 * Controls how highlighted text is rendered in Markdown output.
 */
@SuppressWarnings("PMD")
public enum HighlightStyle {
  /**
   * Double equals syntax (==text==). Default. Pandoc-compatible.
   */
  DoubleEqual("doubleequal"),
  /**
   * Preserve as HTML (==text==). Original HTML tag.
   */
  Html("html"),
  /**
   * Render as bold (**text**). Uses strong emphasis.
   */
  Bold("bold"),
  /**
   * Strip formatting, render as plain text. No markup.
   */
  None("none");

  /** The string value. */
  private final String value;

  HighlightStyle(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static HighlightStyle fromValue(final String value) {
    for (HighlightStyle e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown HighlightStyle value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
