// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new HtmlToMarkdownRsException. */
  public HtmlToMarkdownRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new HtmlToMarkdownRsException with a cause. */
  public HtmlToMarkdownRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
