// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:411256ebae58a5a5ab1b77fe1f91fe158a88eecdc7709575c93a6e4ed499f324
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import org.jspecify.annotations.Nullable;
@SuppressWarnings("PMD")
public final class HtmlToMarkdown {
    private HtmlToMarkdown() { }

    /**
     * Convert HTML to Markdown, Djot, or plain text.
     *
     * Returns a ConversionResult with converted content plus optional metadata,
     * document structure, table data, inline images, and warnings depending on the
     * enabled features and conversion options.
     * {@literal @}param html — the HTML string to convert.
     *
     * {@literal @}param options — conversion options. Rust accepts bare ConversionOptions, {@code Some(options)}, or {@code None}.
     * Language bindings expose the same option fields through native constructors or optional parameters.
     *
     * {@literal @}throws HtmlToMarkdownRsException Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
     */
    public static ConversionResult convert(final String html, final @Nullable ConversionOptions options) throws HtmlToMarkdownRsException {
        java.util.Objects.requireNonNull(html, "html must not be null");
        return HtmlToMarkdownRs.convert(html, options);
    }

    public static ConversionResult convert(final String html) throws HtmlToMarkdownRsException {
        return HtmlToMarkdownRs.convert(html, null);
    }


}
