// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9e875201aaa1463c15e0a241122082d3c23e810863377fbf0f9aab8c635da0e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Exception thrown by HtmlToMarkdownRs. */
public class HtmlToMarkdownRsException extends Exception {
  private static final long serialVersionUID = 1L;
  /** The error code. */
  private final int code;

  /** Creates a new HtmlToMarkdownRsException. */
  public HtmlToMarkdownRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new HtmlToMarkdownRsException with a cause. */
  public HtmlToMarkdownRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
