// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import org.jspecify.annotations.Nullable;
@SuppressWarnings("PMD")
public final class HtmlToMarkdown {
  private HtmlToMarkdown() {}

  /**
   * Convert HTML to Markdown, Djot, or plain text.
   *
   * Returns a ConversionResult with converted content plus optional metadata,
   * document structure, table data, inline images, and warnings depending on
   * the enabled features and conversion options.
   * {@literal @}param html — the HTML string to convert.
   *
   * {@literal @}param options — conversion options. Rust accepts bare
   * ConversionOptions, {@code Some(options)}, or {@code None}. Language
   * bindings expose the same option fields through native constructors or
   * optional parameters.
   *
   * {@literal @}throws HtmlToMarkdownRsException Returns an error if HTML
   * parsing fails or if the input contains invalid UTF-8.
   *
   * # Observability
   *
   * Emits an {@code html_to_markdown.convert} span at {@code INFO} level with
   * fields {@code input_len},
   * {@code output_format}, {@code wrap}, {@code extract_metadata}, {@code
   * extract_images}, and {@code tier_strategy}. These field names are part of
   * the public observability contract and are kept stable across releases. This
   * crate never installs a {@code tracing} subscriber — attach one in the
   * consuming application to observe these spans and events.
   */
  public static ConversionResult convert(final String html, final
                                         @Nullable ConversionOptions options)
      throws HtmlToMarkdownRsException {
    java.util.Objects.requireNonNull(html, "html must not be null");
    return HtmlToMarkdownRs.convert(html, options);
  }

  public static ConversionResult convert(final String html)
      throws HtmlToMarkdownRsException {
    return HtmlToMarkdownRs.convert(html, null);
  }
}
