// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:455ba5aaa9cd8ade9e1c3afed6ac55afe55f72b613df4c6725eff0a29a8f9f8b
// To regenerate: alef generate
// To verify freshness: alef verify

package io.xberg.htmltomarkdown;

import java.util.List;

/**
 * Bridge interface for the HtmlVisitor plugin system.
 *
 * Implementations are wrapped by HtmlVisitorBridge and exposed to the native
 * runtime through Panama FFM upcall stubs.
 */
public interface IHtmlVisitor {

/** visit_text. */    VisitResult visit_text(String _ctx, String _text) throws Exception;

/** visit_element_start. */    VisitResult visit_element_start(String _ctx) throws Exception;

/** visit_element_end. */    VisitResult visit_element_end(String _ctx, String _output) throws Exception;

/** visit_link. */    VisitResult visit_link(String _ctx, String _href, String _text, String _title) throws Exception;

/** visit_image. */    VisitResult visit_image(String _ctx, String _src, String _alt, String _title) throws Exception;

/** visit_heading. */    VisitResult visit_heading(String _ctx, int _level, String _text, String _id) throws Exception;

/** visit_code_block. */    VisitResult visit_code_block(String _ctx, String _lang, String _code) throws Exception;

/** visit_code_inline. */    VisitResult visit_code_inline(String _ctx, String _code) throws Exception;

/** visit_list_item. */    VisitResult visit_list_item(String _ctx, boolean _ordered, String _marker, String _text) throws Exception;

/** visit_list_start. */    VisitResult visit_list_start(String _ctx, boolean _ordered) throws Exception;

/** visit_list_end. */    VisitResult visit_list_end(String _ctx, boolean _ordered, String _output) throws Exception;

/** visit_table_start. */    VisitResult visit_table_start(String _ctx) throws Exception;

/** visit_table_row. */    VisitResult visit_table_row(String _ctx, List<String> _cells, boolean _is_header) throws Exception;

/** visit_table_end. */    VisitResult visit_table_end(String _ctx, String _output) throws Exception;

/** visit_blockquote. */    VisitResult visit_blockquote(String _ctx, String _content, long _depth) throws Exception;

/** visit_strong. */    VisitResult visit_strong(String _ctx, String _text) throws Exception;

/** visit_emphasis. */    VisitResult visit_emphasis(String _ctx, String _text) throws Exception;

/** visit_strikethrough. */    VisitResult visit_strikethrough(String _ctx, String _text) throws Exception;

/** visit_underline. */    VisitResult visit_underline(String _ctx, String _text) throws Exception;

/** visit_subscript. */    VisitResult visit_subscript(String _ctx, String _text) throws Exception;

/** visit_superscript. */    VisitResult visit_superscript(String _ctx, String _text) throws Exception;

/** visit_mark. */    VisitResult visit_mark(String _ctx, String _text) throws Exception;

/** visit_line_break. */    VisitResult visit_line_break(String _ctx) throws Exception;

/** visit_horizontal_rule. */    VisitResult visit_horizontal_rule(String _ctx) throws Exception;

/** visit_custom_element. */    VisitResult visit_custom_element(String _ctx, String _tag_name, String _html) throws Exception;

/** visit_definition_list_start. */    VisitResult visit_definition_list_start(String _ctx) throws Exception;

/** visit_definition_term. */    VisitResult visit_definition_term(String _ctx, String _text) throws Exception;

/** visit_definition_description. */    VisitResult visit_definition_description(String _ctx, String _text) throws Exception;

/** visit_definition_list_end. */    VisitResult visit_definition_list_end(String _ctx, String _output) throws Exception;

/** visit_form. */    VisitResult visit_form(String _ctx, String _action, String _method) throws Exception;

/** visit_input. */    VisitResult visit_input(String _ctx, String _input_type, String _name, String _value) throws Exception;

/** visit_button. */    VisitResult visit_button(String _ctx, String _text) throws Exception;

/** visit_audio. */    VisitResult visit_audio(String _ctx, String _src) throws Exception;

/** visit_video. */    VisitResult visit_video(String _ctx, String _src) throws Exception;

/** visit_iframe. */    VisitResult visit_iframe(String _ctx, String _src) throws Exception;

/** visit_details. */    VisitResult visit_details(String _ctx, boolean _open) throws Exception;

/** visit_summary. */    VisitResult visit_summary(String _ctx, String _text) throws Exception;

/** visit_figure_start. */    VisitResult visit_figure_start(String _ctx) throws Exception;

/** visit_figcaption. */    VisitResult visit_figcaption(String _ctx, String _text) throws Exception;

/** visit_figure_end. */    VisitResult visit_figure_end(String _ctx, String _output) throws Exception;
}
