// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image source classification for proper handling and processing.
 *
 * Determines whether an image is embedded (data URI), inline SVG, external, or
 * relative.
 */
@SuppressWarnings("PMD")
public enum ImageType {
  /**
   * Data URI embedded image (base64 or other encoding)
   */
  DataUri("data_uri"),
  /**
   * Inline SVG element
   */
  InlineSvg("inline_svg"),
  /**
   * External image URL (http/https)
   */
  External("external"),
  /**
   * Relative image path
   */
  Relative("relative");

  /** The string value. */
  private final String value;

  ImageType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static ImageType fromValue(final String value) {
    for (ImageType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown ImageType value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
