// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2a958f79b47283c5d38e497ad5b5acc5d0751a599fc13f65abb88d2bdd6a33a2
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image source classification for proper handling and processing.
 *
 * Determines whether an image is embedded (data URI), inline SVG, external, or relative.
 */
@SuppressWarnings("PMD")
public enum ImageType {
    /**
     * Data URI embedded image (base64 or other encoding)
     */
    DataUri("data_uri"),
    /**
     * Inline SVG element
     */
    InlineSvg("inline_svg"),
    /**
     * External image URL (http/https)
     */
    External("external"),
    /**
     * Relative image path
     */
    Relative("relative");


    /** The string value. */
    private final String value;

    ImageType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ImageType fromValue(final String value) {
        for (ImageType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ImageType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
