// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ed4b359577c60e49d179f2ada11b3e7c123f74c5b045685336184c80dbc4c2b6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Image dimensions in pixels.
 *
 * Binding-safe replacement for {@code (u32, u32)} tuples, which degrade to
 * {@code Vec&lt;Vec&lt;String&gt;&gt;} when sanitized for cross-language binding generation.
 * Used by both {@code ImageMetadata} and
 * {@code InlineImage}.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageDimensions.Builder.class)
public record ImageDimensions(
    @JsonProperty("width") int width,
    @JsonProperty("height") int height
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for ImageDimensions deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private int width;
        private int height;

        /** Sets the width field. */
        @JsonProperty("width")
        public Builder withWidth(final int value) {
            this.width = value;
            return this;
        }

        /** Sets the height field. */
        @JsonProperty("height")
        public Builder withHeight(final int value) {
            this.height = value;
            return this;
        }

        /** Constructs a ImageDimensions instance from the builder's current state. */
        public ImageDimensions build() {
            return new ImageDimensions(
                width,
                height
            );
        }
    }
    // CPD-ON
}
