// DO NOT EDIT - auto-generated by alef
// alef:hash:8796bd112d92cbfaf40e0ddac56e9289fdb6dae6100a8f257ef949830c723a7f
package io.xberg.htmltomarkdown;

/**
 * Invalid input data
 */
public class InvalidInputException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException with the given message. */
  public InvalidInputException(final String message) {
    super(message);
  }

  /** Creates a new InvalidInputException with the given message and cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
