// DO NOT EDIT - auto-generated by alef
// alef:hash:232b103e3ebfb83c836de6cc0ab33776f8cb9c04d653b571f3dfe4765e8e8cea
package io.xberg.htmltomarkdown;

/**
 * Invalid input data
 */
public class InvalidInputException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException with the given message. */
  public InvalidInputException(final String message) {
    super(message);
  }

  /** Creates a new InvalidInputException with the given message and cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
