// DO NOT EDIT - auto-generated by alef
// alef:hash:6e27cbd7c3f5f8845992c5d5d8ecb539f525b7d5d1a91cd355a3d393dd6f0a18
package io.xberg.htmltomarkdown;

/**
 * Invalid input data
 */
public class InvalidInputException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException with the given message. */
  public InvalidInputException(final String message) {
    super(message);
  }

  /** Creates a new InvalidInputException with the given message and cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
