// DO NOT EDIT - auto-generated by alef
// alef:hash:50fc917bff61aabcb2d655af66e57cc055f548036d66c61242cdad0e0e1860f1
package io.xberg.htmltomarkdown;

/**
 * I/O error — stores the error message string so the variant is FFI-safe.
 *
 * Use `ConversionError::from(io_error)` to convert from `std::io::Error`.
 */
public class IoErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoErrorException with the given message. */
  public IoErrorException(final String message) {
    super(message);
  }

  /** Creates a new IoErrorException with the given message and cause. */
  public IoErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
