// DO NOT EDIT - auto-generated by alef
// alef:hash:d7e43bee0f92cf98f0172fdba47ef0c2b65bf1fad9f2cd75327f9293bcb37ad1
package io.xberg.htmltomarkdown;

/**
 * I/O error — stores the error message string so the variant is FFI-safe.
 *
 * Use `ConversionError::from(io_error)` to convert from `std::io::Error`.
 */
public class IoErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoErrorException with the given message. */
  public IoErrorException(final String message) {
    super(message);
  }

  /** Creates a new IoErrorException with the given message and cause. */
  public IoErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
