// DO NOT EDIT - auto-generated by alef
// alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
package io.xberg.htmltomarkdown;

/**
 * I/O error — stores the error message string so the variant is FFI-safe.
 *
 * Use `ConversionError::from(io_error)` to convert from `std::io::Error`.
 */
public class IoErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoErrorException with the given message. */
  public IoErrorException(final String message) { super(message); }

  /** Creates a new IoErrorException with the given message and cause. */
  public IoErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
