// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link classification based on href value and document context.
 *
 * Used to categorize links during extraction for filtering and analysis.
 */
@SuppressWarnings("PMD")
public enum LinkType {
    /**
     * Anchor link within same document (href starts with #)
     */
    Anchor("anchor"),
    /**
     * Internal link within same domain
     */
    Internal("internal"),
    /**
     * External link to different domain
     */
    External("external"),
    /**
     * Email link (mailto:)
     */
    Email("email"),
    /**
     * Phone link (tel:)
     */
    Phone("phone"),
    /**
     * Other protocol or unclassifiable
     */
    Other("other");


    /** The string value. */
    private final String value;

    LinkType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static LinkType fromValue(final String value) {
        for (LinkType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown LinkType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
