// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Link classification based on href value and document context.
 *
 * Used to categorize links during extraction for filtering and analysis.
 */
@SuppressWarnings("PMD")
public enum LinkType {
  /**
   * Anchor link within same document (href starts with #)
   */
  Anchor("anchor"),
  /**
   * Internal link within same domain
   */
  Internal("internal"),
  /**
   * External link to different domain
   */
  External("external"),
  /**
   * Email link (mailto:)
   */
  Email("email"),
  /**
   * Phone link (tel:)
   */
  Phone("phone"),
  /**
   * Other protocol or unclassifiable
   */
  Other("other");

  /** The string value. */
  private final String value;

  LinkType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static LinkType fromValue(final String value) {
    for (LinkType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown LinkType value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
