// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b29145cdf8b535272542b22e74fa127d508fe6b6b10f53600ce7e16d511c6a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * List indentation character type.
 *
 * Controls whether list items are indented with spaces or tabs.
 */
@SuppressWarnings("PMD")
public enum ListIndentType {
    /**
     * Use spaces for indentation. Default. Width controlled by {@code list_indent_width}.
     */
    Spaces("Spaces"),
    /**
     * Use tabs for indentation.
     */
    Tabs("Tabs");


    /** The string value. */
    private final String value;

    ListIndentType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ListIndentType fromValue(final String value) {
        for (ListIndentType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ListIndentType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
