// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:67e8844189f6caef12de5e8155e05a5ee2fab20d7899ab37b6b7686b9b93383e
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Line break syntax in Markdown output.
 *
 * Controls how soft line breaks (from {@code &lt;br&gt;} or line breaks in source) are rendered.
 */
@SuppressWarnings("PMD")
public enum NewlineStyle {
    /**
     * Two trailing spaces at end of line. Default. Standard Markdown syntax.
     */
    Spaces("Spaces"),
    /**
     * Backslash at end of line. Alternative Markdown syntax.
     */
    Backslash("Backslash");


    /** The string value. */
    private final String value;

    NewlineStyle(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static NewlineStyle fromValue(final String value) {
        for (NewlineStyle e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown NewlineStyle value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
