// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4f50a89b244fa93f9d7ec25b092b0aca90f3ebacd05d24494c8309f3dd702d1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Line break syntax in Markdown output.
 *
 * Controls how soft line breaks (from {@code &lt;br&gt;} or line breaks in
 * source) are rendered.
 */
@SuppressWarnings("PMD")
public enum NewlineStyle {
  /**
   * Two trailing spaces at end of line. Default. Standard Markdown syntax.
   */
  Spaces("spaces"),
  /**
   * Backslash at end of line. Alternative Markdown syntax.
   */
  Backslash("backslash");

  /** The string value. */
  private final String value;

  NewlineStyle(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static NewlineStyle fromValue(final String value) {
    for (NewlineStyle e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown NewlineStyle value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
