// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:19071a8709846e3bbd47b7b834616ee008b85cf9faf0f788e7e1e18c2bd7868e
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Node type enumeration covering all HTML element types.
 *
 * This enum categorizes all HTML elements that the converter recognizes,
 * providing a coarse-grained classification for visitor dispatch.
 */
@SuppressWarnings("PMD")
public enum NodeType {
    /**
     * Text node (most frequent - 100+ per document)
     */
    Text("Text"),
    /**
     * Generic element node
     */
    Element("Element"),
    /**
     * Heading elements (h1-h6)
     */
    Heading("Heading"),
    /**
     * Paragraph element
     */
    Paragraph("Paragraph"),
    /**
     * Generic div container
     */
    Div("Div"),
    /**
     * Blockquote element
     */
    Blockquote("Blockquote"),
    /**
     * Preformatted text block
     */
    Pre("Pre"),
    /**
     * Horizontal rule
     */
    Hr("Hr"),
    /**
     * Ordered or unordered list (ul, ol)
     */
    List("List"),
    /**
     * List item (li)
     */
    ListItem("ListItem"),
    /**
     * Definition list (dl)
     */
    DefinitionList("DefinitionList"),
    /**
     * Definition term (dt)
     */
    DefinitionTerm("DefinitionTerm"),
    /**
     * Definition description (dd)
     */
    DefinitionDescription("DefinitionDescription"),
    /**
     * Table element
     */
    Table("Table"),
    /**
     * Table row (tr)
     */
    TableRow("TableRow"),
    /**
     * Table cell (td, th)
     */
    TableCell("TableCell"),
    /**
     * Table header cell (th)
     */
    TableHeader("TableHeader"),
    /**
     * Table body (tbody)
     */
    TableBody("TableBody"),
    /**
     * Table head (thead)
     */
    TableHead("TableHead"),
    /**
     * Table foot (tfoot)
     */
    TableFoot("TableFoot"),
    /**
     * Anchor link (a)
     */
    Link("Link"),
    /**
     * Image (img)
     */
    Image("Image"),
    /**
     * Strong/bold (strong, b)
     */
    Strong("Strong"),
    /**
     * Emphasis/italic (em, i)
     */
    Em("Em"),
    /**
     * Inline code (code)
     */
    Code("Code"),
    /**
     * Strikethrough (s, del, strike)
     */
    Strikethrough("Strikethrough"),
    /**
     * Underline (u, ins)
     */
    Underline("Underline"),
    /**
     * Subscript (sub)
     */
    Subscript("Subscript"),
    /**
     * Superscript (sup)
     */
    Superscript("Superscript"),
    /**
     * Mark/highlight (mark)
     */
    Mark("Mark"),
    /**
     * Small text (small)
     */
    Small("Small"),
    /**
     * Line break (br)
     */
    Br("Br"),
    /**
     * Span element
     */
    Span("Span"),
    /**
     * Article element
     */
    Article("Article"),
    /**
     * Section element
     */
    Section("Section"),
    /**
     * Navigation element
     */
    Nav("Nav"),
    /**
     * Aside element
     */
    Aside("Aside"),
    /**
     * Header element
     */
    Header("Header"),
    /**
     * Footer element
     */
    Footer("Footer"),
    /**
     * Main element
     */
    Main("Main"),
    /**
     * Figure element
     */
    Figure("Figure"),
    /**
     * Figure caption
     */
    Figcaption("Figcaption"),
    /**
     * Time element
     */
    Time("Time"),
    /**
     * Details element
     */
    Details("Details"),
    /**
     * Summary element
     */
    Summary("Summary"),
    /**
     * Form element
     */
    Form("Form"),
    /**
     * Input element
     */
    Input("Input"),
    /**
     * Select element
     */
    Select("Select"),
    /**
     * Option element
     */
    Option("Option"),
    /**
     * Button element
     */
    Button("Button"),
    /**
     * Textarea element
     */
    Textarea("Textarea"),
    /**
     * Label element
     */
    Label("Label"),
    /**
     * Fieldset element
     */
    Fieldset("Fieldset"),
    /**
     * Legend element
     */
    Legend("Legend"),
    /**
     * Audio element
     */
    Audio("Audio"),
    /**
     * Video element
     */
    Video("Video"),
    /**
     * Picture element
     */
    Picture("Picture"),
    /**
     * Source element
     */
    Source("Source"),
    /**
     * Iframe element
     */
    Iframe("Iframe"),
    /**
     * SVG element
     */
    Svg("Svg"),
    /**
     * Canvas element
     */
    Canvas("Canvas"),
    /**
     * Ruby annotation
     */
    Ruby("Ruby"),
    /**
     * Ruby text
     */
    Rt("Rt"),
    /**
     * Ruby parenthesis
     */
    Rp("Rp"),
    /**
     * Abbreviation
     */
    Abbr("Abbr"),
    /**
     * Keyboard input
     */
    Kbd("Kbd"),
    /**
     * Sample output
     */
    Samp("Samp"),
    /**
     * Variable
     */
    Var("Var"),
    /**
     * Citation
     */
    Cite("Cite"),
    /**
     * Quote
     */
    Q("Q"),
    /**
     * Deleted text
     */
    Del("Del"),
    /**
     * Inserted text
     */
    Ins("Ins"),
    /**
     * Data element
     */
    Data("Data"),
    /**
     * Meter element
     */
    Meter("Meter"),
    /**
     * Progress element
     */
    Progress("Progress"),
    /**
     * Output element
     */
    Output("Output"),
    /**
     * Template element
     */
    Template("Template"),
    /**
     * Slot element
     */
    Slot("Slot"),
    /**
     * HTML root element
     */
    Html("Html"),
    /**
     * Head element
     */
    Head("Head"),
    /**
     * Body element
     */
    Body("Body"),
    /**
     * Title element
     */
    Title("Title"),
    /**
     * Meta element
     */
    Meta("Meta"),
    /**
     * Link element (not anchor)
     */
    LinkTag("LinkTag"),
    /**
     * Style element
     */
    Style("Style"),
    /**
     * Script element
     */
    Script("Script"),
    /**
     * Base element
     */
    Base("Base"),
    /**
     * Custom element (web components) or unknown tag
     */
    Custom("Custom");


    /** The string value. */
    private final String value;

    NodeType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static NodeType fromValue(final String value) {
        for (NodeType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown NodeType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
