// DO NOT EDIT - auto-generated by alef
// alef:hash:38f54eebb4157b9b35e97b0bce4bd79ee98c31cc7f4ac82969c1ce2234fd196f
package io.xberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
