// DO NOT EDIT - auto-generated by alef
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
package io.xberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) { super(message); }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
