// DO NOT EDIT - auto-generated by alef
// alef:hash:68d40b4c4622bf4891df5417fcb1f22407ad229cdb3adbe7d50f12a0b42de404
package io.xberg.htmltomarkdown;

/**
 * Generic conversion error
 */
public class OtherException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OtherException with the given message. */
  public OtherException(final String message) {
    super(message);
  }

  /** Creates a new OtherException with the given message and cause. */
  public OtherException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
