// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4f50a89b244fa93f9d7ec25b092b0aca90f3ebacd05d24494c8309f3dd702d1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Output format for conversion.
 *
 * Specifies the target markup language format for the conversion output.
 */
@SuppressWarnings("PMD")
public enum OutputFormat {
  /**
   * Standard Markdown ({@code CommonMark} compatible). Default.
   */
  Markdown("markdown"),
  /**
   * Djot lightweight markup language.
   */
  Djot("djot"),
  /**
   * Plain text output (no markup, visible text only).
   */
  Plain("plain");

  /** The string value. */
  private final String value;

  OutputFormat(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static OutputFormat fromValue(final String value) {
    for (OutputFormat e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown OutputFormat value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
