// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ac22b029e16fa5c04412e731cdc2e7275a7843a00b304e8934c841eb1f187a75
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Output format for conversion.
 *
 * Specifies the target markup language format for the conversion output.
 */
@SuppressWarnings("PMD")
public enum OutputFormat {
    /**
     * Standard Markdown ({@code CommonMark} compatible). Default.
     */
    Markdown("Markdown"),
    /**
     * Djot lightweight markup language.
     */
    Djot("Djot"),
    /**
     * Plain text output (no markup, visible text only).
     */
    Plain("Plain");


    /** The string value. */
    private final String value;

    OutputFormat(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static OutputFormat fromValue(final String value) {
        for (OutputFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown OutputFormat value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
