// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:441998b5e920254cc97ef8713238f5dab17bc9e4b456a3e2709924f99009c2eb
// To regenerate: alef generate
// To verify freshness: alef verify

/**
 * High-performance HTML to Markdown converter
 */
package io.xberg.htmltomarkdown;
