// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d58ea5d169e4435fbea8d185b78cbd3883441c9e2f87d6471e5b2920180f0f4
// To regenerate: alef generate
// To verify freshness: alef verify

/**
 * High-performance HTML to Markdown converter
 */
package io.xberg.htmltomarkdown;
