// DO NOT EDIT - auto-generated by alef
// alef:hash:1b29145cdf8b535272542b22e74fa127d508fe6b6b10f53600ce7e16d511c6a4
package io.xberg.htmltomarkdown;

/**
 * Panic caught during conversion to prevent unwinding across FFI boundaries
 */
public class PanicException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PanicException with the given message. */
  public PanicException(final String message) {
    super(message);
  }

  /** Creates a new PanicException with the given message and cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
