// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:54c57f5047b7bfaa7c8df9e7220db7e97724a1e11c168867f294316101d890d6
// To regenerate: alef generate
// To verify freshness: alef verify
package io.xberg.htmltomarkdown;

/** Exception thrown when a Rust panic is contained at the FFI boundary. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class PanicException extends HtmlToMarkdownRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PanicException. */
  public PanicException(final String message) {
    super(3, message);
  }

  /** Creates a new PanicException with a cause. */
  public PanicException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
