// DO NOT EDIT - auto-generated by alef
// alef:hash:355bb05ee807e3959b9296739f2a5a238be7f48c4685d4fe80581de360ec8a77
package io.xberg.htmltomarkdown;

/**
 * HTML parsing error
 */
public class ParseErrorException extends ConversionErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParseErrorException with the given message. */
    public ParseErrorException(final String message) {
        super(message);
    }

    /** Creates a new ParseErrorException with the given message and cause. */
    public ParseErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
