// DO NOT EDIT - auto-generated by alef
// alef:hash:b49faaf77fb74e29e6a1721e807cacb54f9b71644b5583732a78cc9126fb68e0
package io.xberg.htmltomarkdown;

/**
 * HTML parsing error
 */
public class ParseErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseErrorException with the given message. */
  public ParseErrorException(final String message) {
    super(message);
  }

  /** Creates a new ParseErrorException with the given message and cause. */
  public ParseErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
