// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * HTML preprocessing options for document cleanup before conversion.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PreprocessingOptions.Builder.class)
public record PreprocessingOptions(
    @JsonProperty("enabled") boolean enabled,
    @JsonProperty("preset") PreprocessingPreset preset,
    @JsonProperty("remove_navigation") boolean removeNavigation,
    @JsonProperty("remove_forms") boolean removeForms) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() { return new Builder(); }

  // CPD-OFF
  /** Jackson builder for PreprocessingOptions deserialization. */
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private boolean enabled = true;
    private PreprocessingPreset preset;
    @JsonProperty("remove_navigation") private boolean removeNavigation = true;
    @JsonProperty("remove_forms") private boolean removeForms = true;

    /** Sets the enabled field. */
    @JsonProperty("enabled")
    public Builder withEnabled(final boolean value) {
      this.enabled = value;
      return this;
    }

    /** Sets the preset field. */
    @JsonProperty("preset")
    public Builder withPreset(final PreprocessingPreset value) {
      this.preset = value;
      return this;
    }

    /** Sets the removeNavigation field. */
    @JsonProperty("remove_navigation")
    public Builder withRemoveNavigation(final boolean value) {
      this.removeNavigation = value;
      return this;
    }

    /** Sets the removeForms field. */
    @JsonProperty("remove_forms")
    public Builder withRemoveForms(final boolean value) {
      this.removeForms = value;
      return this;
    }

    /**
     * Constructs a PreprocessingOptions instance from the builder's current
     * state.
     */
    public PreprocessingOptions build() {
      return new PreprocessingOptions(enabled, preset, removeNavigation,
                                      removeForms);
    }
  }
  // CPD-ON
}
