// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * HTML preprocessing aggressiveness level.
 *
 * Controls the extent of cleanup performed before conversion. Higher levels
 * remove more elements.
 */
@SuppressWarnings("PMD")
public enum PreprocessingPreset {
  /**
   * Minimal cleanup. Remove only essential noise (scripts, styles).
   */
  Minimal("minimal"),
  /**
   * Standard cleanup. Default. Removes navigation, forms, and other auxiliary
   * content.
   */
  Standard("standard"),
  /**
   * Aggressive cleanup. Remove extensive non-content elements and structure.
   */
  Aggressive("aggressive");

  /** The string value. */
  private final String value;

  PreprocessingPreset(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static PreprocessingPreset fromValue(final String value) {
    for (PreprocessingPreset e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown PreprocessingPreset value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
