// DO NOT EDIT - auto-generated by alef
// alef:hash:11b53512ce352fa429b3487113320a2a4a72d302f7a5f4f2ceda41991f6d1847
package io.xberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SanitizationErrorException with the given message. */
  public SanitizationErrorException(final String message) { super(message); }

  /**
   * Creates a new SanitizationErrorException with the given message and cause.
   */
  public SanitizationErrorException(final String message,
                                    final Throwable cause) {
    super(message, cause);
  }
}
