// DO NOT EDIT - auto-generated by alef
// alef:hash:b49faaf77fb74e29e6a1721e807cacb54f9b71644b5583732a78cc9126fb68e0
package io.xberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SanitizationErrorException with the given message. */
  public SanitizationErrorException(final String message) {
    super(message);
  }

  /** Creates a new SanitizationErrorException with the given message and cause. */
  public SanitizationErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
