// DO NOT EDIT - auto-generated by alef
// alef:hash:ed4b359577c60e49d179f2ada11b3e7c123f74c5b045685336184c80dbc4c2b6
package io.xberg.htmltomarkdown;

/**
 * HTML sanitization error
 */
public class SanitizationErrorException extends ConversionErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SanitizationErrorException with the given message. */
  public SanitizationErrorException(final String message) {
    super(message);
  }

  /** Creates a new SanitizationErrorException with the given message and cause. */
  public SanitizationErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
