// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Structured data format type.
 *
 * Identifies the schema/format used for structured data markup.
 */
@SuppressWarnings("PMD")
public enum StructuredDataType {
  /**
   * JSON-LD (JSON for Linking Data) script blocks
   */
  JsonLd("json_ld"),
  /**
   * HTML5 Microdata attributes (itemscope, itemtype, itemprop)
   */
  Microdata("microdata"),
  /**
   * RDF in Attributes ({@code RDFa}) markup
   */
  RDFa("rdfa");

  /** The string value. */
  private final String value;

  StructuredDataType(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static StructuredDataType fromValue(final String value) {
    for (StructuredDataType e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown StructuredDataType value: " +
                                       value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
