// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8d115ad995656db6ec437e434ec942658d69d01ccdf13493bc6ba66f7ec39b71
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A structured table grid with cell-level data including spans.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TableGrid.Builder.class)
public record TableGrid(
    @JsonProperty("rows") int rows,
    @JsonProperty("cols") int cols,
    @JsonProperty("cells") List<GridCell> cells
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for TableGrid deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        private int rows;
        private int cols;
        private List<GridCell> cells = List.of();

        /** Sets the rows field. */
        @JsonProperty("rows")
        public Builder withRows(final int value) {
            this.rows = value;
            return this;
        }

        /** Sets the cols field. */
        @JsonProperty("cols")
        public Builder withCols(final int value) {
            this.cols = value;
            return this;
        }

        /** Sets the cells field. */
        @JsonProperty("cells")
        public Builder withCells(final List<GridCell> value) {
            this.cells = value;
            return this;
        }

        /** Constructs a TableGrid instance from the builder's current state. */
        public TableGrid build() {
            return new TableGrid(
                rows,
                cols,
                cells
            );
        }
    }
    // CPD-ON
}
