// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9e875201aaa1463c15e0a241122082d3c23e810863377fbf0f9aab8c635da0e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

/** Controls how the visitor affects the conversion pipeline. */
@SuppressWarnings("PMD")
public sealed interface VisitResult
        permits VisitResult.Continue, VisitResult.Custom, VisitResult.Skip, VisitResult.PreserveHtml, VisitResult.Error {

    record Continue() implements VisitResult {}

    static VisitResult continue_() {
        return new Continue();
    }
    record Custom(String value) implements VisitResult {}

    static VisitResult custom(String value) {
        return new Custom(value);
    }
    record Skip() implements VisitResult {}

    static VisitResult skip() {
        return new Skip();
    }
    record PreserveHtml() implements VisitResult {}

    static VisitResult preserveHtml() {
        return new PreserveHtml();
    }
    record Error(String value) implements VisitResult {}

    static VisitResult error(String value) {
        return new Error(value);
    }
}
