// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.htmltomarkdown;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Categories of processing warnings.
 */
@SuppressWarnings("PMD")
public enum WarningKind {
  /**
   * An image could not be extracted (e.g. invalid data URI, unsupported
   * format).
   */
  ImageExtractionFailed("image_extraction_failed"),
  /**
   * The input encoding was not recognized; fell back to UTF-8.
   */
  EncodingFallback("encoding_fallback"),
  /**
   * The input was truncated due to size limits.
   */
  TruncatedInput("truncated_input"),
  /**
   * The HTML was malformed but processing continued with best effort.
   */
  MalformedHtml("malformed_html"),
  /**
   * Sanitization was applied to remove potentially unsafe content.
   */
  SanitizationApplied("sanitization_applied"),
  /**
   * DOM traversal was truncated because {@code max_depth} was exceeded.
   */
  DepthLimitExceeded("depth_limit_exceeded");

  /** The string value. */
  private final String value;

  WarningKind(final String value) { this.value = value; }

  /** Returns the string value. */
  @JsonValue
  public String getValue() {
    return value;
  }

  /** Creates an instance from a string value. */
  @JsonCreator
  public static WarningKind fromValue(final String value) {
    for (WarningKind e : values()) {
      if (e.value.equalsIgnoreCase(value)) {
        return e;
      }
    }
    throw new IllegalArgumentException("Unknown WarningKind value: " + value);
  }

  /** Returns the wire-format string value (matches JSON serialization). */
  @Override
  public String toString() {
    return value;
  }
}
