# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81ce7477531ed66bf6f1d4d10108545f47918fc8308edb1bf5b2a46e5280813c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: smoke

test_that("smoke_empty_string: Empty string produces empty output", {
  result <- convert(html = "", options = ConversionOptions$default())
  expect_equal(trimws(result$content), "")
})

test_that("smoke_simple_heading: H1 heading converts to ATX markdown", {
  result <- convert(html = "<h1>Title</h1>", options = ConversionOptions$default())
  expect_true(any(grepl("# Title", result$content, fixed = TRUE)))
})

test_that("smoke_simple_paragraph: Simple paragraph converts correctly", {
  result <- convert(html = "<p>Hello World</p>", options = ConversionOptions$default())
  expect_equal(trimws(result$content), "Hello World")
  expect_true(if (is.character(result$content)) length(result$content) > 0 && any(nchar(result$content) > 0) else length(result$content) > 0)
})
