// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6d884b19f34855f2a1e379a9030cb7d1c179643125099827af10f992eaafefd5
// To regenerate: alef generate
// To verify freshness: alef verify
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import HtmlToMarkdown
import RustBridge

/// E2e tests for category: smoke.
final class SmokeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
    }

    func testSmokeEmptyString() throws {
        // Empty string produces empty output
        let _options = try HtmlToMarkdown.conversionOptionsFromJson("{}")
        let result = try HtmlToMarkdown.convert(html: "", options: _options)
        XCTAssertEqual((result.content()?.toString() ?? ""), "")
    }

    func testSmokeSimpleHeading() throws {
        // H1 heading converts to ATX markdown
        let _options = try HtmlToMarkdown.conversionOptionsFromJson("{}")
        let result = try HtmlToMarkdown.convert(html: "<h1>Title</h1>", options: _options)
        XCTAssertTrue((result.content()?.toString() ?? "").contains("# Title"), "expected to contain: \("# Title")")
    }

    func testSmokeSimpleParagraph() throws {
        // Simple paragraph converts correctly
        let _options = try HtmlToMarkdown.conversionOptionsFromJson("{}")
        let result = try HtmlToMarkdown.convert(html: "<p>Hello World</p>", options: _options)
        XCTAssertEqual((result.content()?.toString() ?? ""), "Hello World")
        XCTAssertTrue(result.content() != nil, "expected non-empty value")
    }

}
