# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:57ab646b2aa585300fc30781ecbe6c39c43ca0b5c48930536a333899655d37db
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

require "mkmf"
require "rb_sys/mkmf"

default_profile = ENV.fetch("CARGO_PROFILE", "release")

create_rust_makefile("html_to_markdown_rb") do |config|
  config.profile = default_profile.to_sym
  # extconf.rb and Cargo.toml are siblings under ext/html_to_markdown_rb/native/; rb_sys interprets
  # ext_dir relative to extconf.rb, so "." finds the sibling Cargo.toml. "native" would
  # resolve to native/native/Cargo.toml and break `gem install` on end-user machines.
  config.ext_dir = "."
end
