<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:411256ebae58a5a5ab1b77fe1f91fe158a88eecdc7709575c93a6e4ed499f324
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace HtmlToMarkdown;

final class HtmlToMarkdown
{
    /**
     * Convert HTML to Markdown, Djot, or plain text.
     *
     * Returns a [`ConversionResult`] with converted content plus optional metadata,
     * document structure, table data, inline images, and warnings depending on the
     * enabled features and conversion options.
     *
     * @param string $html
     * @param ?ConversionOptions $options
     * @return ConversionResult
     * @throws \HtmlToMarkdown\HtmlToMarkdownException
     */
    public static function convert(
        string $html,
        ?ConversionOptions $options = null,
    ): ConversionResult {
        return \HtmlToMarkdown\HtmlToMarkdownApi::convert($html, $options); // delegate to native extension class
    }
}
