<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace HtmlToMarkdown;

/**
 * Shareable, thread-safe handle to a user-provided HTML visitor implementation.
 *
 * Pass an instance wrapped in this handle to `ConversionOptions` to
 * customise how the HTML document is traversed and converted to Markdown.
 * The handle may be cloned and shared across threads without additional
 * synchronisation on the caller's side.
 */
final class VisitorHandle
{
    /**
     * Wrap a PHP object implementing the visitor interface as a shareable handle.
     */
    public static function from_php_object(object $visitor): self
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
