<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace HtmlToMarkdown;

/**
 * Shareable, thread-safe handle to a user-provided HTML visitor implementation.
 *
 * Pass an instance wrapped in this handle to `ConversionOptions` to
 * customise how the HTML document is traversed and converted to Markdown.
 * The handle may be cloned and shared across threads without additional
 * synchronisation on the caller's side.
 */
final class VisitorHandle
{
    /**
     * Wrap a PHP object implementing the visitor interface as a shareable handle.
     */
    public static function from_php_object(object $visitor): self
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
