# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc3df0961194e1a83c2033eac62de5e08e1e3a20bb08bab378b021eb370bc0d4
# To regenerate: alef generate
# To verify freshness: alef verify
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
