# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3730f30022f245ae564b2978411fff9a279ba5524f18980105fdc2d910626d7e
# To regenerate: alef generate
# To verify freshness: alef verify

# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "html-to-markdown"
  spec.version = "3.11.5"
  spec.authors       = ["Na'aman Hirschfeld <naaman@xberg.io>"]
  spec.summary       = "High-performance HTML to Markdown converter"
  spec.description   = "High-performance HTML to Markdown converter"
  spec.homepage      = "https://github.com/xberg-io/html-to-markdown"

  spec.license       = "MIT"

  spec.required_ruby_version = ">= 3.2.0"
  spec.metadata["keywords"] = %w[converter html markdown].join(",")
  spec.metadata["rubygems_mfa_required"] = "true"

  candidate_files    = Dir.glob(%w[README* LICENSE* lib/**/* ext/**/* sig/**/* Steepfile]).select { |f| File.file?(f) }
  spec.files         = candidate_files.grep_v(%r{/(?:target|tmp)/|\.(?:bundle|so|dylib|dll|o|a|log)\z|\.dSYM/})
  spec.require_paths = ["lib"]
  spec.extensions    = ["ext/html_to_markdown_rb/native/extconf.rb"]

  spec.add_dependency "rb_sys", ">= 0.9", "< 0.9.128"
  spec.add_dependency "sorbet-runtime", "~> 0.5"
end
