/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
#include <html_to_markdown.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  const char *version = htm_version();

  if (!version || strlen(version) == 0) {
    fprintf(stderr, "FAIL: expected non-empty version string\n");
    return 1;
  }

  printf("PASS: htm_version returned: %s\n", version);
  return 0;
}
