/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:411256ebae58a5a5ab1b77fe1f91fe158a88eecdc7709575c93a6e4ed499f324
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
#include <html_to_markdown.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(void) {
  const char *version = htm_version();

  if (!version || strlen(version) == 0) {
    fprintf(stderr, "FAIL: expected non-empty version string\n");
    return 1;
  }

  printf("PASS: htm_version returned: %s\n", version);
  return 0;
}
