# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:653d1e2793d038d23eeb4694cc26f63256c34521ac54400083da50226ab9976e
# To regenerate: alef generate
# To verify freshness: alef verify
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
