# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8d115ad995656db6ec437e434ec942658d69d01ccdf13493bc6ba66f7ec39b71
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
