# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a5b48234964e55343869e9e9ef85d40fe97c2e58d55cda4f66fd80d4e0d01c0e
# To regenerate: alef generate
# To verify freshness: alef verify
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
