// Generated by alef. Do not edit by hand.
// alef:hash:9e0cee838192b11494b33b87e3b82b1f9a98565e7b2016d209b5d1e81b9bd1d7

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-rs-e2e"
