// Generated by alef. Do not edit by hand.
// alef:hash:e42cfa74c78badf374ad9e7fb9eab1bb492edbe033797ebc14dc6176398f2cdc

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-rs-e2e"
