// Generated by alef. Do not edit by hand.
// alef:hash:9564ed7ca69aca87b024d2381f9835c31f90d4a156c7d56b003fad1a83732343

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "html-to-markdown-rs-e2e"
