# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f3736c095f7f17e9c66ed20fbe6847aaa372859b5b5ab79be2e333d63ca246b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require_relative "html_to_markdown/version"
require_relative "html_to_markdown/native"

# Top-level namespace for the HtmlToMarkdown Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "html_to_markdown/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module HtmlToMarkdown
  # Re-export all types and functions from native extension
end

# Keep generated types under HtmlToMarkdown. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
