# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "html_to_markdown/version"
require_relative "html_to_markdown/native"

# Top-level namespace for the HtmlToMarkdown Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "html_to_markdown/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module HtmlToMarkdown
  # Re-export all types and functions from native extension
end

# Keep generated types under HtmlToMarkdown. Publishing generated constants
# into Object makes generic names collide with unrelated Ruby libraries.
