# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:11b53512ce352fa429b3487113320a2a4a72d302f7a5f4f2ceda41991f6d1847
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "html_to_markdown/version"
require_relative "html_to_markdown/native"

# Top-level namespace for the HtmlToMarkdown Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "html_to_markdown/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module HtmlToMarkdown
  # Re-export all types and functions from native extension
end

# Bring top-level HtmlToMarkdown classes into the global namespace so callers
# (and the generated e2e suite) can reference them unqualified. The native
# extension has already been required above, so every type constant is defined
# under HtmlToMarkdown by this point.
HtmlToMarkdown.constants.each do |const_name|
  value = HtmlToMarkdown.const_get(const_name)
  ::Object.const_set(const_name, value) if value.is_a?(Module) && !::Object.const_defined?(const_name)
end
