# Generated by alef. Do not edit by hand.
# alef:hash:f44000653901d10b61e9069d2e901a11b70b0e643ba63d75f2222729c924ae82
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.android.** { *; }
