# Generated by alef. Do not edit by hand.
# alef:hash:411256ebae58a5a5ab1b77fe1f91fe158a88eecdc7709575c93a6e4ed499f324
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.android.** { *; }
