# Generated by alef. Do not edit by hand.
# alef:hash:355bb05ee807e3959b9296739f2a5a238be7f48c4685d4fe80581de360ec8a77
# Keep generated public API for consumers using R8/ProGuard.
-keep class io.xberg.android.** { *; }
