# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.AnnotationKind do
  @moduledoc """
  The type of an inline text annotation.

  Uses internally tagged representation (`"annotation_type": "bold"`) for JSON serialization.
  """

  @typedoc "The type of an inline text annotation."
  @type t :: term()

  @typedoc "Bold / strong emphasis."
  @type bold :: :bold
  @typedoc "Italic / emphasis."
  @type italic :: :italic
  @typedoc "Underline."
  @type underline :: :underline
  @typedoc "Strikethrough / deleted text."
  @type strikethrough :: :strikethrough
  @typedoc "Inline code."
  @type code :: :code
  @typedoc "Subscript text."
  @type subscript :: :subscript
  @typedoc "Superscript text."
  @type superscript :: :superscript
  @typedoc "Highlighted / marked text."
  @type highlight :: :highlight
  @typedoc "A hyperlink sourced from an `<a href=\"...\">` element."
  @type link :: %{type: :link, url: String.t(), title: String.t()}

  def link(url, title), do: {:link, %{url: url, title: title}}
end
