# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ccaad82816694e9914e98e7e08cea661b6b14ee068815d0565c4a5046599b99
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: HtmlToMarkdown.NodeContent.t(),
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          annotations: [HtmlToMarkdown.TextAnnotation.t()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
