# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:272e5cf42f327186b25205674a55a7136fa3561b4f96647fa29a5618aff88b2f
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc """
  A structured document tree representing the semantic content of an HTML document.

  Uses a flat node array with index-based parent/child references for efficient traversal.
  """

  @typedoc "A structured document tree representing the semantic content of an HTML document."
  @type t :: %__MODULE__{
          nodes: [HtmlToMarkdown.DocumentNode.t()],
          source_format: String.t() | nil
        }

  defstruct nodes: [],
            source_format: nil
end
