# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b49faaf77fb74e29e6a1721e807cacb54f9b71644b5583732a78cc9126fb68e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
  id: String.t() | nil,
  content: String.t() | nil,
  parent: non_neg_integer() | nil,
  children: [non_neg_integer()],
  annotations: [HtmlToMarkdown.TextAnnotation.t()],
  attributes: map() | nil
  }

  defstruct id: nil,
  content: :heading,
  parent: nil,
  children: [],
  annotations: [],
  attributes: nil
end
