# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fc94d0fc91558047424415908200d795e49b8225ebe48653e2192a00344f213
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc """
  A structured document tree representing the semantic content of an HTML document.

  Uses a flat node array with index-based parent/child references for efficient traversal.
  """

  @typedoc "A structured document tree representing the semantic content of an HTML document."
  @type t :: %__MODULE__{
          nodes: [HtmlToMarkdown.DocumentNode.t()],
          source_format: String.t() | nil
        }

  defstruct nodes: [],
            source_format: nil
end
