# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:064a6aa15d732f87a1dbe6b84970bc9399e86f7be4fa15b279da262566ac14f8
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.DocumentStructure do
  @moduledoc """
  A structured document tree representing the semantic content of an HTML document.

  Uses a flat node array with index-based parent/child references for efficient traversal.
  """

  @typedoc "A structured document tree representing the semantic content of an HTML document."
  @type t :: %__MODULE__{
          nodes: [HtmlToMarkdown.DocumentNode.t()],
          source_format: String.t() | nil
        }

  defstruct nodes: [],
            source_format: nil
end
