# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e07bbfe24302cc189a08b2d54795628827c8957ccf29ca51383a80a09e2d32a0
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.DocumentNode do
  @moduledoc "A single node in the document tree."

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: HtmlToMarkdown.NodeContent.t(),
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          annotations: [HtmlToMarkdown.TextAnnotation.t()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: :heading,
            parent: nil,
            children: [],
            annotations: [],
            attributes: nil
end
