# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83efd795d1ecf49c53fe954d08050eb3f3cc5eebe00f6e49714ac7cbc12d5683
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  @typedoc "A single cell in a table grid."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row: non_neg_integer(),
          col: non_neg_integer(),
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean()
        }

  defstruct content: nil,
            row: 0,
            col: 0,
            row_span: nil,
            col_span: nil,
            is_header: false
end
