# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f0f83a7f0ec95e9fa6c14023596214a907e0d582a13cd8979fb46cd5f72db15c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  @typedoc "A single cell in a table grid."
  @type t :: %__MODULE__{
  content: String.t() | nil,
  row: non_neg_integer(),
  col: non_neg_integer(),
  row_span: non_neg_integer(),
  col_span: non_neg_integer(),
  is_header: boolean()
  }

  defstruct content: nil,
  row: 0,
  col: 0,
  row_span: 0,
  col_span: 0,
  is_header: false
end
