# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:355bb05ee807e3959b9296739f2a5a238be7f48c4685d4fe80581de360ec8a77
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.GridCell do
  @moduledoc "A single cell in a table grid."

  @typedoc "A single cell in a table grid."
  @type t :: %__MODULE__{
  content: String.t() | nil,
  row: non_neg_integer(),
  col: non_neg_integer(),
  row_span: non_neg_integer(),
  col_span: non_neg_integer(),
  is_header: boolean()
  }

  defstruct content: nil,
  row: 0,
  col: 0,
  row_span: 0,
  col_span: 0,
  is_header: false
end
