# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.HeadingStyle do
  @moduledoc """
  Heading style options for Markdown output.

  Controls how headings (h1-h6) are rendered in the output Markdown.
  """

  @typedoc "Heading style options for Markdown output."
  @type t :: :underlined | :atx | :atx_closed

  @underlined :underlined
  @atx :atx
  @atx_closed :atx_closed

  @doc "Underlined style (=== for h1, --- for h2)."
  @spec underlined() :: t()
  def underlined, do: @underlined
  @doc "ATX style (# for h1, ## for h2, etc.). Default."
  @spec atx() :: t()
  def atx, do: @atx
  @doc "ATX closed style (# title #, with closing hashes)."
  @spec atx_closed() :: t()
  def atx_closed, do: @atx_closed
end
