# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:69f806c1a20b6a18911d35912634fdb69c0558e10fcf8d1720821f1d8f7dd8c2
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.HighlightStyle do
  @moduledoc """
  Highlight rendering style for `<mark>` elements.

  Controls how highlighted text is rendered in Markdown output.
  """

  @typedoc "Highlight rendering style for `<mark>` elements."
  @type t :: :double_equal | :html | :bold | :none

  @double_equal :double_equal
  @html :html
  @bold :bold
  @none :none

  @doc "Double equals syntax (==text==). Default. Pandoc-compatible."
  @spec double_equal() :: t()
  def double_equal, do: @double_equal
  @doc "Preserve as HTML (==text==). Original HTML tag."
  @spec html() :: t()
  def html, do: @html
  @doc "Render as bold (**text**). Uses strong emphasis."
  @spec bold() :: t()
  def bold, do: @bold
  @doc "Strip formatting, render as plain text. No markup."
  @spec none() :: t()
  def none, do: @none

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:double_equal), do: "DoubleEqual"
  def wire_value(:html), do: "Html"
  def wire_value(:bold), do: "Bold"
  def wire_value(:none), do: "None"
end
