# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.HighlightStyle do
  @moduledoc """
  Highlight rendering style for `<mark>` elements.

  Controls how highlighted text is rendered in Markdown output.
  """

  @typedoc "Highlight rendering style for `<mark>` elements."
  @type t :: :double_equal | :html | :bold | :none

  @double_equal :double_equal
  @html :html
  @bold :bold
  @none :none

  @doc "Double equals syntax (==text==). Default. Pandoc-compatible."
  @spec double_equal() :: t()
  def double_equal, do: @double_equal
  @doc "Preserve as HTML (==text==). Original HTML tag."
  @spec html() :: t()
  def html, do: @html
  @doc "Render as bold (**text**). Uses strong emphasis."
  @spec bold() :: t()
  def bold, do: @bold
  @doc "Strip formatting, render as plain text. No markup."
  @spec none() :: t()
  def none, do: @none
end
