# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e875201aaa1463c15e0a241122082d3c23e810863377fbf0f9aab8c635da0e6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.HtmlMetadata do
  @moduledoc """
  Comprehensive metadata extraction result from HTML document.

  Contains all extracted metadata types in a single structure,
  suitable for serialization and transmission across language boundaries.

  # Examples

  ```
  let metadata = HtmlMetadata {
      document: Default::default(),
      headers: Vec::new(),
      links: Vec::new(),
      images: Vec::new(),
      structured_data: Vec::new(),
  };

  assert!(metadata.headers.is_empty());
  ```
  """

  @typedoc "Comprehensive metadata extraction result from HTML document."
  @type t :: %__MODULE__{
          document: HtmlToMarkdown.DocumentMetadata.t(),
          headers: [HtmlToMarkdown.HeaderMetadata.t()],
          links: [HtmlToMarkdown.LinkMetadata.t()],
          images: [HtmlToMarkdown.ImageMetadata.t()],
          structured_data: [HtmlToMarkdown.StructuredData.t()]
        }

  defstruct document: nil,
            headers: [],
            links: [],
            images: [],
            structured_data: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
