# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ImageDimensions do
  @moduledoc """
  Image dimensions in pixels.

  Binding-safe replacement for `(u32, u32)` tuples, which degrade to
  `Vec<Vec<String>>` when sanitized for cross-language binding generation.
  Used by both `ImageMetadata` and
  `InlineImage`.
  """

  @typedoc "Image dimensions in pixels."
  @type t :: %__MODULE__{
  width: non_neg_integer(),
  height: non_neg_integer()
  }

  defstruct width: 0,
  height: 0
end
