# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ImageMetadata do
  @moduledoc """
  Image metadata with source and dimensions.

  Captures `<img>` elements and inline `<svg>` elements with metadata
  for image analysis and optimization.

  # Examples

  ```
  let img = ImageMetadata {
      src: "https://example.com/image.jpg".to_string(),
      alt: Some("An example image".to_string()),
      title: Some("Example".to_string()),
      dimensions: Some(ImageDimensions { width: 800, height: 600 }),
      image_type: ImageType::External,
      attributes: Default::default(),
  };

  assert_eq!(img.image_type, ImageType::External);
  ```
  """

  @typedoc "Image metadata with source and dimensions."
  @type t :: %__MODULE__{
  src: String.t() | nil,
  alt: String.t() | nil,
  title: String.t() | nil,
  dimensions: HtmlToMarkdown.ImageDimensions.t() | nil,
  image_type: String.t() | nil,
  attributes: map()
  }

  defstruct src: nil,
  alt: nil,
  title: nil,
  dimensions: nil,
  image_type: :data_uri,
  attributes: %{}
end
