# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed4b359577c60e49d179f2ada11b3e7c123f74c5b045685336184c80dbc4c2b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ImageType do
  @moduledoc """
  Image source classification for proper handling and processing.

  Determines whether an image is embedded (data URI), inline SVG, external, or relative.
  """

  @typedoc "Image source classification for proper handling and processing."
  @type t :: :data_uri | :inline_svg | :external | :relative

  @data_uri :data_uri
  @inline_svg :inline_svg
  @external :external
  @relative :relative

  @doc "Data URI embedded image (base64 or other encoding)"
  @spec data_uri() :: t()
  def data_uri, do: @data_uri
  @doc "Inline SVG element"
  @spec inline_svg() :: t()
  def inline_svg, do: @inline_svg
  @doc "External image URL (http/https)"
  @spec external() :: t()
  def external, do: @external
  @doc "Relative image path"
  @spec relative() :: t()
  def relative, do: @relative
end
