# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ecd4afac3d92f58249e3720d7542ea1a764dd0ea1c84bbfcf3a27d215af82c87
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.ImageMetadata do
  @moduledoc """
  Image metadata with source and dimensions.

  Captures `<img>` elements and inline `<svg>` elements with metadata
  for image analysis and optimization.

  # Examples

  ```
  let img = ImageMetadata {
      src: "https://example.com/image.jpg".to_string(),
      alt: Some("An example image".to_string()),
      title: Some("Example".to_string()),
      dimensions: Some(ImageDimensions { width: 800, height: 600 }),
      image_type: ImageType::External,
      attributes: Default::default(),
  };

  assert_eq!(img.image_type, ImageType::External);
  ```
  """

  @typedoc "Image metadata with source and dimensions."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          dimensions: HtmlToMarkdown.ImageDimensions.t() | nil,
          image_type: HtmlToMarkdown.ImageType.t(),
          attributes: map()
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: %{}
end
