# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9e875201aaa1463c15e0a241122082d3c23e810863377fbf0f9aab8c635da0e6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ImageDimensions do
  @moduledoc """
  Image dimensions in pixels.

  Binding-safe replacement for `(u32, u32)` tuples, which degrade to
  `Vec<Vec<String>>` when sanitized for cross-language binding generation.
  Used by both `ImageMetadata` and
  `InlineImage`.
  """

  @typedoc "Image dimensions in pixels."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct width: 0,
            height: 0
end
