# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce2712cf8aa3128a43b13001ca7c0df56aaf42dca7e0d08e83c5b003ea2ddb34
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.ImageDimensions do
  @moduledoc """
  Image dimensions in pixels.

  Binding-safe replacement for `(u32, u32)` tuples, which degrade to
  `Vec<Vec<String>>` when sanitized for cross-language binding generation.
  Used by both `ImageMetadata` and
  `InlineImage`.
  """

  @typedoc "Image dimensions in pixels."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct width: 0,
            height: 0
end
