# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4f50a89b244fa93f9d7ec25b092b0aca90f3ebacd05d24494c8309f3dd702d1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.LinkStyle do
  @moduledoc """
  Link rendering style in Markdown output.

  Controls whether links and images use inline `[text](url)` syntax or
  reference-style `[text][1]` syntax with definitions collected at the end.
  """

  @typedoc "Link rendering style in Markdown output."
  @type t :: :inline | :reference

  @inline :inline
  @reference :reference

  @doc "Inline links: `[text](url)`. Default."
  @spec inline() :: t()
  def inline, do: @inline
  @doc "Reference-style links: `[text][1]` with `[1]: url` at end of document."
  @spec reference() :: t()
  def reference, do: @reference
end
