# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7b694046c2a4748c5ce3f8fbb3dd5e70b44c670c0a53412bbdd5c1a78ac82b58
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.LinkType do
  @moduledoc """
  Link classification based on href value and document context.

  Used to categorize links during extraction for filtering and analysis.
  """

  @typedoc "Link classification based on href value and document context."
  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @doc "Anchor link within same document (href starts with #)"
  @spec anchor() :: t()
  def anchor, do: @anchor
  @doc "Internal link within same domain"
  @spec internal() :: t()
  def internal, do: @internal
  @doc "External link to different domain"
  @spec external() :: t()
  def external, do: @external
  @doc "Email link (mailto:)"
  @spec email() :: t()
  def email, do: @email
  @doc "Phone link (tel:)"
  @spec phone() :: t()
  def phone, do: @phone
  @doc "Other protocol or unclassifiable"
  @spec other() :: t()
  def other, do: @other

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:anchor), do: "anchor"
  def wire_value(:internal), do: "internal"
  def wire_value(:external), do: "external"
  def wire_value(:email), do: "email"
  def wire_value(:phone), do: "phone"
  def wire_value(:other), do: "other"
end
