# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:79f8a032661f1f5516a8029d098b433919836afee2cc252c5bacd131e4334ce9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.LinkMetadata do
  @moduledoc """
  Hyperlink metadata with categorization and attributes.

  Represents `<a>` elements with parsed href values, text content, and link type classification.

  # Examples

  ```
  let link = LinkMetadata {
      href: "https://example.com".to_string(),
      text: "Example".to_string(),
      title: Some("Visit Example".to_string()),
      link_type: LinkType::External,
      rel: vec!["nofollow".to_string()],
      attributes: Default::default(),
  };

  assert_eq!(link.link_type, LinkType::External);
  assert_eq!(link.text, "Example");
  ```
  """

  @typedoc "Hyperlink metadata with categorization and attributes."
  @type t :: %__MODULE__{
          href: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil,
          link_type: HtmlToMarkdown.LinkType.t(),
          rel: [String.t()],
          attributes: map()
        }

  defstruct href: nil,
            text: nil,
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: %{}
end
