# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:94dd1be9921f0c99181696abdb7a25b59df4f9229ed5f05876faf9831bbba0f5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ListIndentType do
  @moduledoc """
  List indentation character type.

  Controls whether list items are indented with spaces or tabs.
  """

  @typedoc "List indentation character type."
  @type t :: :spaces | :tabs

  @spaces :spaces
  @tabs :tabs

  @doc "Use spaces for indentation. Default. Width controlled by `list_indent_width`."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Use tabs for indentation."
  @spec tabs() :: t()
  def tabs, do: @tabs
end
