# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0e6d7cfc88c44de94bedd231aad5d7251e74e9be4176a5b8112a613ea117f47
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.MetadataEntry do
  @moduledoc """
  A single key-value metadata entry from `<head>` meta tags.

  Binding-safe replacement for `(String, String)` tuples used in
  [`NodeContent::MetadataBlock`]. Tuple pairs cannot be represented
  across language boundaries without lossy degradation.
  """

  @typedoc "A single key-value metadata entry from `<head>` meta tags."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil
end
