# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:baeaf79dfad2433c7fe23ec48c488103d6239fbc49ba3012695b25799113595a
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.MetadataEntry do
  @moduledoc """
  A single key-value metadata entry from `<head>` meta tags.

  Binding-safe replacement for `(String, String)` tuples used in
  [`NodeContent::MetadataBlock`]. Tuple pairs cannot be represented
  across language boundaries without lossy degradation.
  """

  @typedoc "A single key-value metadata entry from `<head>` meta tags."
  @type t :: %__MODULE__{
          key: String.t() | nil,
          value: String.t() | nil
        }

  defstruct key: nil,
            value: nil
end
