# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2fa08fc697236b22148a8cf6fe0f4b9f449c9cdc33a9d160f22c077cc55faeb
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.NewlineStyle do
  @moduledoc """
  Line break syntax in Markdown output.

  Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
  """

  @typedoc "Line break syntax in Markdown output."
  @type t :: :spaces | :backslash

  @spaces :spaces
  @backslash :backslash

  @doc "Two trailing spaces at end of line. Default. Standard Markdown syntax."
  @spec spaces() :: t()
  def spaces, do: @spaces
  @doc "Backslash at end of line. Alternative Markdown syntax."
  @spec backslash() :: t()
  def backslash, do: @backslash
end
