# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e52351fb65d0164b2408c00bff99c69b5aa4a4d967502f05f87f9e9a24d04bd
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.NodeContent do
  @moduledoc """
  The semantic content type of a document node.

  Uses internally tagged representation (`"node_type": "heading"`) for JSON serialization.
  """

  @typedoc "The semantic content type of a document node."
  @type t :: term()

  @typedoc "A heading element (h1-h6)."
  @type heading :: %{node_type: :heading, level: non_neg_integer(), text: String.t()}
  @typedoc "A paragraph of text."
  @type paragraph :: %{node_type: :paragraph, text: String.t()}
  @typedoc "A list container (ordered or unordered). Children are `ListItem` nodes."
  @type list_variant :: %{node_type: :list, ordered: boolean()}
  @typedoc "A single list item."
  @type list_item :: %{node_type: :list_item, text: String.t()}
  @typedoc "A table with structured cell data."
  @type table :: %{node_type: :table, grid: HtmlToMarkdown.TableGrid.t()}
  @typedoc "An image element."
  @type image :: %{node_type: :image, description: String.t(), src: String.t(), image_index: non_neg_integer()}
  @typedoc "A code block or inline code."
  @type code :: %{node_type: :code, text: String.t(), language: String.t()}
  @typedoc "A block quote container."
  @type quote :: :quote
  @typedoc "A definition list container."
  @type definition_list :: :definition_list
  @typedoc "A definition list entry with term and description."
  @type definition_item :: %{node_type: :definition_item, term: String.t(), definition: String.t()}
  @typedoc "A raw block preserved as-is (e.g. `<script>`, `<style>` content)."
  @type raw_block :: %{node_type: :raw_block, format: String.t(), content: String.t()}
  @typedoc "A block of key-value metadata pairs (from `<head>` meta tags)."
  @type metadata_block :: %{node_type: :metadata_block, entries: [map()]}
  @typedoc "A section grouping container (auto-generated from heading hierarchy)."
  @type group :: %{node_type: :group, label: String.t(), heading_level: non_neg_integer(), heading_text: String.t()}

  def heading(level, text), do: {:heading, %{level: level, text: text}}
  def paragraph(text), do: {:paragraph, %{text: text}}
  def list(ordered), do: {:list, %{ordered: ordered}}
  def list_item(text), do: {:list_item, %{text: text}}
  def table(grid), do: {:table, %{grid: grid}}
  def image(description, src, image_index), do: {:image, %{description: description, src: src, image_index: image_index}}
  def code(text, language), do: {:code, %{text: text, language: language}}
  def definition_item(term, definition), do: {:definition_item, %{term: term, definition: definition}}
  def raw_block(format, content), do: {:raw_block, %{format: format, content: content}}
  def metadata_block(entries), do: {:metadata_block, %{entries: entries}}
  def group(label, heading_level, heading_text), do: {:group, %{label: label, heading_level: heading_level, heading_text: heading_text}}

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:heading), do: "heading"
  def wire_value(:paragraph), do: "paragraph"
  def wire_value(:list), do: "list"
  def wire_value(:list_item), do: "list_item"
  def wire_value(:table), do: "table"
  def wire_value(:image), do: "image"
  def wire_value(:code), do: "code"
  def wire_value(:quote), do: "quote"
  def wire_value(:definition_list), do: "definition_list"
  def wire_value(:definition_item), do: "definition_item"
  def wire_value(:raw_block), do: "raw_block"
  def wire_value(:metadata_block), do: "metadata_block"
  def wire_value(:group), do: "group"
  def wire_value(value) when is_tuple(value), do: wire_value(elem(value, 0))
end
