# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:23f6601fa30a62b6a9230161c2d28218a4d8fe4ea90949f01841925bbd99ccfe
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.NodeType do
  @moduledoc """
  Node type enumeration covering all HTML element types.

  This enum categorizes all HTML elements that the converter recognizes,
  providing a coarse-grained classification for visitor dispatch.
  """

  @typedoc "Node type enumeration covering all HTML element types."
  @type t ::
          :text
          | :element
          | :heading
          | :paragraph
          | :div
          | :blockquote
          | :pre
          | :hr
          | :list
          | :list_item
          | :definition_list
          | :definition_term
          | :definition_description
          | :table
          | :table_row
          | :table_cell
          | :table_header
          | :table_body
          | :table_head
          | :table_foot
          | :link
          | :image
          | :strong
          | :em
          | :code
          | :strikethrough
          | :underline
          | :subscript
          | :superscript
          | :mark
          | :small
          | :br
          | :span
          | :article
          | :section
          | :nav
          | :aside
          | :header
          | :footer
          | :main
          | :figure
          | :figcaption
          | :time
          | :details
          | :summary
          | :form
          | :input
          | :select
          | :option
          | :button
          | :textarea
          | :label
          | :fieldset
          | :legend
          | :audio
          | :video
          | :picture
          | :source
          | :iframe
          | :svg
          | :canvas
          | :ruby
          | :rt
          | :rp
          | :abbr
          | :kbd
          | :samp
          | :var
          | :cite
          | :q
          | :del
          | :ins
          | :data
          | :meter
          | :progress
          | :output
          | :template
          | :slot
          | :html
          | :head
          | :body
          | :title
          | :meta
          | :link_tag
          | :style
          | :script
          | :base
          | :custom

  @text :text
  @element :element
  @heading :heading
  @paragraph :paragraph
  @div :div
  @blockquote :blockquote
  @pre :pre
  @hr :hr
  @list :list
  @list_item :list_item
  @definition_list :definition_list
  @definition_term :definition_term
  @definition_description :definition_description
  @table :table
  @table_row :table_row
  @table_cell :table_cell
  @table_header :table_header
  @table_body :table_body
  @table_head :table_head
  @table_foot :table_foot
  @link :link
  @image :image
  @strong :strong
  @em :em
  @code :code
  @strikethrough :strikethrough
  @underline :underline
  @subscript :subscript
  @superscript :superscript
  @mark :mark
  @small :small
  @br :br
  @span :span
  @article :article
  @section :section
  @nav :nav
  @aside :aside
  @header :header
  @footer :footer
  @main :main
  @figure :figure
  @figcaption :figcaption
  @time :time
  @details :details
  @summary :summary
  @form :form
  @input :input
  @select :select
  @option :option
  @button :button
  @textarea :textarea
  @label :label
  @fieldset :fieldset
  @legend :legend
  @audio :audio
  @video :video
  @picture :picture
  @source :source
  @iframe :iframe
  @svg :svg
  @canvas :canvas
  @ruby :ruby
  @rt :rt
  @rp :rp
  @abbr :abbr
  @kbd :kbd
  @samp :samp
  @var :var
  @cite :cite
  @q :q
  @del :del
  @ins :ins
  @data :data
  @meter :meter
  @progress :progress
  @output :output
  @template :template
  @slot :slot
  @html :html
  @head :head
  @body :body
  @title :title
  @meta :meta
  @link_tag :link_tag
  @style :style
  @script :script
  @base :base
  @custom :custom

  @doc "Text node (most frequent - 100+ per document)"
  @spec text() :: t()
  def text, do: @text
  @doc "Generic element node"
  @spec element() :: t()
  def element, do: @element
  @doc "Heading elements (h1-h6)"
  @spec heading() :: t()
  def heading, do: @heading
  @doc "Paragraph element"
  @spec paragraph() :: t()
  def paragraph, do: @paragraph
  @doc "Generic div container"
  @spec div() :: t()
  def div, do: @div
  @doc "Blockquote element"
  @spec blockquote() :: t()
  def blockquote, do: @blockquote
  @doc "Preformatted text block"
  @spec pre() :: t()
  def pre, do: @pre
  @doc "Horizontal rule"
  @spec hr() :: t()
  def hr, do: @hr
  @doc "Ordered or unordered list (ul, ol)"
  @spec list() :: t()
  def list, do: @list
  @doc "List item (li)"
  @spec list_item() :: t()
  def list_item, do: @list_item
  @doc "Definition list (dl)"
  @spec definition_list() :: t()
  def definition_list, do: @definition_list
  @doc "Definition term (dt)"
  @spec definition_term() :: t()
  def definition_term, do: @definition_term
  @doc "Definition description (dd)"
  @spec definition_description() :: t()
  def definition_description, do: @definition_description
  @doc "Table element"
  @spec table() :: t()
  def table, do: @table
  @doc "Table row (tr)"
  @spec table_row() :: t()
  def table_row, do: @table_row
  @doc "Table cell (td, th)"
  @spec table_cell() :: t()
  def table_cell, do: @table_cell
  @doc "Table header cell (th)"
  @spec table_header() :: t()
  def table_header, do: @table_header
  @doc "Table body (tbody)"
  @spec table_body() :: t()
  def table_body, do: @table_body
  @doc "Table head (thead)"
  @spec table_head() :: t()
  def table_head, do: @table_head
  @doc "Table foot (tfoot)"
  @spec table_foot() :: t()
  def table_foot, do: @table_foot
  @doc "Anchor link (a)"
  @spec link() :: t()
  def link, do: @link
  @doc "Image (img)"
  @spec image() :: t()
  def image, do: @image
  @doc "Strong/bold (strong, b)"
  @spec strong() :: t()
  def strong, do: @strong
  @doc "Emphasis/italic (em, i)"
  @spec em() :: t()
  def em, do: @em
  @doc "Inline code (code)"
  @spec code() :: t()
  def code, do: @code
  @doc "Strikethrough (s, del, strike)"
  @spec strikethrough() :: t()
  def strikethrough, do: @strikethrough
  @doc "Underline (u, ins)"
  @spec underline() :: t()
  def underline, do: @underline
  @doc "Subscript (sub)"
  @spec subscript() :: t()
  def subscript, do: @subscript
  @doc "Superscript (sup)"
  @spec superscript() :: t()
  def superscript, do: @superscript
  @doc "Mark/highlight (mark)"
  @spec mark() :: t()
  def mark, do: @mark
  @doc "Small text (small)"
  @spec small() :: t()
  def small, do: @small
  @doc "Line break (br)"
  @spec br() :: t()
  def br, do: @br
  @doc "Span element"
  @spec span() :: t()
  def span, do: @span
  @doc "Article element"
  @spec article() :: t()
  def article, do: @article
  @doc "Section element"
  @spec section() :: t()
  def section, do: @section
  @doc "Navigation element"
  @spec nav() :: t()
  def nav, do: @nav
  @doc "Aside element"
  @spec aside() :: t()
  def aside, do: @aside
  @doc "Header element"
  @spec header() :: t()
  def header, do: @header
  @doc "Footer element"
  @spec footer() :: t()
  def footer, do: @footer
  @doc "Main element"
  @spec main() :: t()
  def main, do: @main
  @doc "Figure element"
  @spec figure() :: t()
  def figure, do: @figure
  @doc "Figure caption"
  @spec figcaption() :: t()
  def figcaption, do: @figcaption
  @doc "Time element"
  @spec time() :: t()
  def time, do: @time
  @doc "Details element"
  @spec details() :: t()
  def details, do: @details
  @doc "Summary element"
  @spec summary() :: t()
  def summary, do: @summary
  @doc "Form element"
  @spec form() :: t()
  def form, do: @form
  @doc "Input element"
  @spec input() :: t()
  def input, do: @input
  @doc "Select element"
  @spec select() :: t()
  def select, do: @select
  @doc "Option element"
  @spec option() :: t()
  def option, do: @option
  @doc "Button element"
  @spec button() :: t()
  def button, do: @button
  @doc "Textarea element"
  @spec textarea() :: t()
  def textarea, do: @textarea
  @doc "Label element"
  @spec label() :: t()
  def label, do: @label
  @doc "Fieldset element"
  @spec fieldset() :: t()
  def fieldset, do: @fieldset
  @doc "Legend element"
  @spec legend() :: t()
  def legend, do: @legend
  @doc "Audio element"
  @spec audio() :: t()
  def audio, do: @audio
  @doc "Video element"
  @spec video() :: t()
  def video, do: @video
  @doc "Picture element"
  @spec picture() :: t()
  def picture, do: @picture
  @doc "Source element"
  @spec source() :: t()
  def source, do: @source
  @doc "Iframe element"
  @spec iframe() :: t()
  def iframe, do: @iframe
  @doc "SVG element"
  @spec svg() :: t()
  def svg, do: @svg
  @doc "Canvas element"
  @spec canvas() :: t()
  def canvas, do: @canvas
  @doc "Ruby annotation"
  @spec ruby() :: t()
  def ruby, do: @ruby
  @doc "Ruby text"
  @spec rt() :: t()
  def rt, do: @rt
  @doc "Ruby parenthesis"
  @spec rp() :: t()
  def rp, do: @rp
  @doc "Abbreviation"
  @spec abbr() :: t()
  def abbr, do: @abbr
  @doc "Keyboard input"
  @spec kbd() :: t()
  def kbd, do: @kbd
  @doc "Sample output"
  @spec samp() :: t()
  def samp, do: @samp
  @doc "Variable"
  @spec var() :: t()
  def var, do: @var
  @doc "Citation"
  @spec cite() :: t()
  def cite, do: @cite
  @doc "Quote"
  @spec q() :: t()
  def q, do: @q
  @doc "Deleted text"
  @spec del() :: t()
  def del, do: @del
  @doc "Inserted text"
  @spec ins() :: t()
  def ins, do: @ins
  @doc "Data element"
  @spec data() :: t()
  def data, do: @data
  @doc "Meter element"
  @spec meter() :: t()
  def meter, do: @meter
  @doc "Progress element"
  @spec progress() :: t()
  def progress, do: @progress
  @doc "Output element"
  @spec output() :: t()
  def output, do: @output
  @doc "Template element"
  @spec template() :: t()
  def template, do: @template
  @doc "Slot element"
  @spec slot() :: t()
  def slot, do: @slot
  @doc "HTML root element"
  @spec html() :: t()
  def html, do: @html
  @doc "Head element"
  @spec head() :: t()
  def head, do: @head
  @doc "Body element"
  @spec body() :: t()
  def body, do: @body
  @doc "Title element"
  @spec title() :: t()
  def title, do: @title
  @doc "Meta element"
  @spec meta() :: t()
  def meta, do: @meta
  @doc "Link element (not anchor)"
  @spec link_tag() :: t()
  def link_tag, do: @link_tag
  @doc "Style element"
  @spec style() :: t()
  def style, do: @style
  @doc "Script element"
  @spec script() :: t()
  def script, do: @script
  @doc "Base element"
  @spec base() :: t()
  def base, do: @base
  @doc "Custom element (web components) or unknown tag"
  @spec custom() :: t()
  def custom, do: @custom

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:text), do: "Text"
  def wire_value(:element), do: "Element"
  def wire_value(:heading), do: "Heading"
  def wire_value(:paragraph), do: "Paragraph"
  def wire_value(:div), do: "Div"
  def wire_value(:blockquote), do: "Blockquote"
  def wire_value(:pre), do: "Pre"
  def wire_value(:hr), do: "Hr"
  def wire_value(:list), do: "List"
  def wire_value(:list_item), do: "ListItem"
  def wire_value(:definition_list), do: "DefinitionList"
  def wire_value(:definition_term), do: "DefinitionTerm"
  def wire_value(:definition_description), do: "DefinitionDescription"
  def wire_value(:table), do: "Table"
  def wire_value(:table_row), do: "TableRow"
  def wire_value(:table_cell), do: "TableCell"
  def wire_value(:table_header), do: "TableHeader"
  def wire_value(:table_body), do: "TableBody"
  def wire_value(:table_head), do: "TableHead"
  def wire_value(:table_foot), do: "TableFoot"
  def wire_value(:link), do: "Link"
  def wire_value(:image), do: "Image"
  def wire_value(:strong), do: "Strong"
  def wire_value(:em), do: "Em"
  def wire_value(:code), do: "Code"
  def wire_value(:strikethrough), do: "Strikethrough"
  def wire_value(:underline), do: "Underline"
  def wire_value(:subscript), do: "Subscript"
  def wire_value(:superscript), do: "Superscript"
  def wire_value(:mark), do: "Mark"
  def wire_value(:small), do: "Small"
  def wire_value(:br), do: "Br"
  def wire_value(:span), do: "Span"
  def wire_value(:article), do: "Article"
  def wire_value(:section), do: "Section"
  def wire_value(:nav), do: "Nav"
  def wire_value(:aside), do: "Aside"
  def wire_value(:header), do: "Header"
  def wire_value(:footer), do: "Footer"
  def wire_value(:main), do: "Main"
  def wire_value(:figure), do: "Figure"
  def wire_value(:figcaption), do: "Figcaption"
  def wire_value(:time), do: "Time"
  def wire_value(:details), do: "Details"
  def wire_value(:summary), do: "Summary"
  def wire_value(:form), do: "Form"
  def wire_value(:input), do: "Input"
  def wire_value(:select), do: "Select"
  def wire_value(:option), do: "Option"
  def wire_value(:button), do: "Button"
  def wire_value(:textarea), do: "Textarea"
  def wire_value(:label), do: "Label"
  def wire_value(:fieldset), do: "Fieldset"
  def wire_value(:legend), do: "Legend"
  def wire_value(:audio), do: "Audio"
  def wire_value(:video), do: "Video"
  def wire_value(:picture), do: "Picture"
  def wire_value(:source), do: "Source"
  def wire_value(:iframe), do: "Iframe"
  def wire_value(:svg), do: "Svg"
  def wire_value(:canvas), do: "Canvas"
  def wire_value(:ruby), do: "Ruby"
  def wire_value(:rt), do: "Rt"
  def wire_value(:rp), do: "Rp"
  def wire_value(:abbr), do: "Abbr"
  def wire_value(:kbd), do: "Kbd"
  def wire_value(:samp), do: "Samp"
  def wire_value(:var), do: "Var"
  def wire_value(:cite), do: "Cite"
  def wire_value(:q), do: "Q"
  def wire_value(:del), do: "Del"
  def wire_value(:ins), do: "Ins"
  def wire_value(:data), do: "Data"
  def wire_value(:meter), do: "Meter"
  def wire_value(:progress), do: "Progress"
  def wire_value(:output), do: "Output"
  def wire_value(:template), do: "Template"
  def wire_value(:slot), do: "Slot"
  def wire_value(:html), do: "Html"
  def wire_value(:head), do: "Head"
  def wire_value(:body), do: "Body"
  def wire_value(:title), do: "Title"
  def wire_value(:meta), do: "Meta"
  def wire_value(:link_tag), do: "LinkTag"
  def wire_value(:style), do: "Style"
  def wire_value(:script), do: "Script"
  def wire_value(:base), do: "Base"
  def wire_value(:custom), do: "Custom"
end
