# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca145fae1c1546ee0070198b0a9770617a3954a1920ee4a0161f7570456acae9
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.OutputFormat do
  @moduledoc """
  Output format for conversion.

  Specifies the target markup language format for the conversion output.
  """

  @typedoc "Output format for conversion."
  @type t :: :markdown | :djot | :plain

  @markdown :markdown
  @djot :djot
  @plain :plain

  @doc "Standard Markdown (`CommonMark` compatible). Default."
  @spec markdown() :: t()
  def markdown, do: @markdown
  @doc "Djot lightweight markup language."
  @spec djot() :: t()
  def djot, do: @djot
  @doc "Plain text output (no markup, visible text only)."
  @spec plain() :: t()
  def plain, do: @plain

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:markdown), do: "Markdown"
  def wire_value(:djot), do: "Djot"
  def wire_value(:plain), do: "Plain"
end
