# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b49faaf77fb74e29e6a1721e807cacb54f9b71644b5583732a78cc9126fb68e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc """
  Partial update for `PreprocessingOptions`.

  This struct uses `Option<T>` to represent optional fields that can be selectively updated.
  Only specified fields (Some values) will override existing options; None values leave the
  corresponding fields unchanged when applied via [`PreprocessingOptions::apply_update`].
  """

  @typedoc "Partial update for `PreprocessingOptions`."
  @type t :: %__MODULE__{
  enabled: boolean() | nil,
  preset: String.t() | nil | nil,
  remove_navigation: boolean() | nil,
  remove_forms: boolean() | nil
  }

  defstruct enabled: nil,
  preset: nil,
  remove_navigation: nil,
  remove_forms: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
