# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.PreprocessingOptions do
  @moduledoc "HTML preprocessing options for document cleanup before conversion."

  @typedoc "HTML preprocessing options for document cleanup before conversion."
  @type t :: %__MODULE__{
  enabled: boolean(),
  preset: String.t() | nil,
  remove_navigation: boolean(),
  remove_forms: boolean()
  }

  defstruct enabled: true,
  preset: :standard,
  remove_navigation: true,
  remove_forms: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
