# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91edc80f02ff8a140b084504d8281ed0c78240f5a71ee90accac4f1a90cf6e1c
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.PreprocessingOptionsUpdate do
  @moduledoc """
  Partial update for `PreprocessingOptions`.

  This struct uses `Option<T>` to represent optional fields that can be selectively updated.
  Only specified fields (Some values) will override existing options; None values leave the
  corresponding fields unchanged when applied via [`PreprocessingOptions::apply_update`].
  """

  @typedoc "Partial update for `PreprocessingOptions`."
  @type t :: %__MODULE__{
          enabled: boolean() | nil,
          preset: HtmlToMarkdown.PreprocessingPreset.t() | nil,
          remove_navigation: boolean() | nil,
          remove_forms: boolean() | nil
        }

  defstruct enabled: nil,
            preset: nil,
            remove_navigation: nil,
            remove_forms: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
