# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:710006b7ef19412f1a7fe6e6bec4739ba6b7ee90eb15a5c12942c0f0eede27e6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.PreprocessingPreset do
  @moduledoc """
  HTML preprocessing aggressiveness level.

  Controls the extent of cleanup performed before conversion. Higher levels remove more elements.
  """

  @typedoc "HTML preprocessing aggressiveness level."
  @type t :: :minimal | :standard | :aggressive

  @minimal :minimal
  @standard :standard
  @aggressive :aggressive

  @doc "Minimal cleanup. Remove only essential noise (scripts, styles)."
  @spec minimal() :: t()
  def minimal, do: @minimal
  @doc "Standard cleanup. Default. Removes navigation, forms, and other auxiliary content."
  @spec standard() :: t()
  def standard, do: @standard
  @doc "Aggressive cleanup. Remove extensive non-content elements and structure."
  @spec aggressive() :: t()
  def aggressive, do: @aggressive

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:minimal), do: "Minimal"
  def wire_value(:standard), do: "Standard"
  def wire_value(:aggressive), do: "Aggressive"
end
