# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.ProcessingWarning do
  @moduledoc """
  A non-fatal diagnostic produced during HTML conversion.

  Warnings indicate that conversion completed but some content may have been handled
  differently than expected — for example, an image that could not be extracted, a truncated
  input, or malformed HTML that was repaired with best-effort parsing.

  Conversion always succeeds (returns `ConversionResult`) even when warnings are
  present. Callers should inspect `warnings` and decide how to
  handle them based on their tolerance for partial results:

  - **Logging pipelines**: emit each warning at `WARN` level and continue.
  - **Strict pipelines**: treat any warning as a hard error by checking
    `result.warnings.is_empty()` before using the output.

  See [`WarningKind`] for the full taxonomy of warning categories.
  """

  @typedoc "A non-fatal diagnostic produced during HTML conversion."
  @type t :: %__MODULE__{
  message: String.t() | nil,
  kind: String.t() | nil
  }

  defstruct message: nil,
  kind: :image_extraction_failed
end
