# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c8c47140175b5de822d3edffc8e2ca9f5fef47d4372aa4c40166a44a646c2c67
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.StructuredDataType do
  @moduledoc """
  Structured data format type.

  Identifies the schema/format used for structured data markup.
  """

  @typedoc "Structured data format type."
  @type t :: :json_ld | :microdata | :rdfa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD (JSON for Linking Data) script blocks"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "HTML5 Microdata attributes (itemscope, itemtype, itemprop)"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDF in Attributes (`RDFa`) markup"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:json_ld), do: "json_ld"
  def wire_value(:microdata), do: "microdata"
  def wire_value(:rd_fa), do: "rdfa"
end
