# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:01a5bec9d013cf8c769445a6021faf30100c3602977bcd6325a44ff3130db423
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.StructuredDataType do
  @moduledoc """
  Structured data format type.

  Identifies the schema/format used for structured data markup.
  """

  @typedoc "Structured data format type."
  @type t :: :json_ld | :microdata | :rdfa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD (JSON for Linking Data) script blocks"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "HTML5 Microdata attributes (itemscope, itemtype, itemprop)"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDF in Attributes (`RDFa`) markup"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
