# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:313e9b3f44bf66c22b3508cc9d8c7bb3b234f403eaccc001eba0fef2c9ba6601
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.StructuredDataType do
  @moduledoc """
  Structured data format type.

  Identifies the schema/format used for structured data markup.
  """

  @typedoc "Structured data format type."
  @type t :: :json_ld | :microdata | :rdfa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD (JSON for Linking Data) script blocks"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "HTML5 Microdata attributes (itemscope, itemtype, itemprop)"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDF in Attributes (`RDFa`) markup"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
