# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5335a07df68a880d2b56bd2a090afec581e1e9847c048cdcc244bb58f5075033
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.StructuredData do
  @moduledoc """
  Structured data block (JSON-LD, Microdata, or `RDFa`).

  Represents machine-readable structured data found in the document.
  JSON-LD blocks are collected as raw JSON strings for flexibility.

  # Examples

  ```
  let schema = StructuredData {
      data_type: StructuredDataType::JsonLd,
      raw_json: r#"{"@context":"https://schema.org","@type":"Article"}"#.to_string(),
      schema_type: Some("Article".to_string()),
  };

  assert_eq!(schema.data_type, StructuredDataType::JsonLd);
  ```
  """

  @typedoc "Structured data block (JSON-LD, Microdata, or `RDFa`)."
  @type t :: %__MODULE__{
          data_type: HtmlToMarkdown.StructuredDataType.t(),
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
