# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6654cad8fd4d8fa0914ec17dcca82229240e55713417730e9b5152b87298c4aa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: HtmlToMarkdown.TableGrid.t(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
