# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4a6f3b98c7e5026926524c3e4c82e811c67954841ab3cc7ef683bcca0f892709
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.TableGrid do
  @moduledoc "A structured table grid with cell-level data including spans."

  @typedoc "A structured table grid with cell-level data including spans."
  @type t :: %__MODULE__{
          rows: non_neg_integer(),
          cols: non_neg_integer(),
          cells: [HtmlToMarkdown.GridCell.t()]
        }

  defstruct rows: 0,
            cols: 0,
            cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
