# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fe65212ff82e334bfd492225c7d37fd111d8129c9cbfa82cbb4897d3d7426d43
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
          grid: HtmlToMarkdown.TableGrid.t(),
          markdown: String.t() | nil
        }

  defstruct grid: nil,
            markdown: nil
end
