# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.TableData do
  @moduledoc "A top-level extracted table with both structured data and markdown representation."

  @typedoc "A top-level extracted table with both structured data and markdown representation."
  @type t :: %__MODULE__{
  grid: HtmlToMarkdown.TableGrid.t(),
  markdown: String.t() | nil
  }

  defstruct grid: nil,
  markdown: nil
end
