# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9862035f54cfed5930cd230827d6adf5be0d982eced75b062228db2778965ef6
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.TextDirection do
  @moduledoc """
  Text directionality of document content.

  Corresponds to the HTML `dir` attribute and `bdi` element directionality.
  """

  @typedoc "Text directionality of document content."
  @type t :: :left_to_right | :right_to_left | :auto

  @left_to_right :left_to_right
  @right_to_left :right_to_left
  @auto :auto

  @doc "Left-to-right text flow (default for Latin scripts)"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text flow (Hebrew, Arabic, Urdu, etc.)"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic directionality detection"
  @spec auto() :: t()
  def auto, do: @auto

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:left_to_right), do: "ltr"
  def wire_value(:right_to_left), do: "rtl"
  def wire_value(:auto), do: "auto"
end
