# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:99a69886561ad09a20711a1f228b1babfc2e04df650e032cc8c0fbbb40d367b5
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.TextDirection do
  @moduledoc """
  Text directionality of document content.

  Corresponds to the HTML `dir` attribute and `bdi` element directionality.
  """

  @typedoc "Text directionality of document content."
  @type t :: :ltr | :rtl | :auto

  @left_to_right :ltr
  @right_to_left :rtl
  @auto :auto

  @doc "Left-to-right text flow (default for Latin scripts)"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text flow (Hebrew, Arabic, Urdu, etc.)"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic directionality detection"
  @spec auto() :: t()
  def auto, do: @auto
end
