# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.VisitorHandle do
  @moduledoc """
  Shareable, thread-safe handle to a user-provided HTML visitor implementation.

  Pass an instance wrapped in this handle to `ConversionOptions` to
  customise how the HTML document is traversed and converted to Markdown.
  The handle may be cloned and shared across threads without additional
  synchronisation on the caller's side.
  """

  defstruct [:ref]

  @typedoc "Shareable, thread-safe handle to a user-provided HTML visitor implementation."
  @type t :: %__MODULE__{ref: reference()}
end
