# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb0e7b3a0d88cc5959bc50cdba1a6c6dfc8cebb1f31f1d11a192f3debd704697
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.WarningKind do
  @moduledoc "Categories of processing warnings."

  @typedoc "Categories of processing warnings."
  @type t ::
          :image_extraction_failed
          | :encoding_fallback
          | :truncated_input
          | :malformed_html
          | :sanitization_applied
          | :depth_limit_exceeded

  @image_extraction_failed :image_extraction_failed
  @encoding_fallback :encoding_fallback
  @truncated_input :truncated_input
  @malformed_html :malformed_html
  @sanitization_applied :sanitization_applied
  @depth_limit_exceeded :depth_limit_exceeded

  @doc "An image could not be extracted (e.g. invalid data URI, unsupported format)."
  @spec image_extraction_failed() :: t()
  def image_extraction_failed, do: @image_extraction_failed
  @doc "The input encoding was not recognized; fell back to UTF-8."
  @spec encoding_fallback() :: t()
  def encoding_fallback, do: @encoding_fallback
  @doc "The input was truncated due to size limits."
  @spec truncated_input() :: t()
  def truncated_input, do: @truncated_input
  @doc "The HTML was malformed but processing continued with best effort."
  @spec malformed_html() :: t()
  def malformed_html, do: @malformed_html
  @doc "Sanitization was applied to remove potentially unsafe content."
  @spec sanitization_applied() :: t()
  def sanitization_applied, do: @sanitization_applied
  @doc "DOM traversal was truncated because `max_depth` was exceeded."
  @spec depth_limit_exceeded() :: t()
  def depth_limit_exceeded, do: @depth_limit_exceeded

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:image_extraction_failed), do: "image_extraction_failed"
  def wire_value(:encoding_fallback), do: "encoding_fallback"
  def wire_value(:truncated_input), do: "truncated_input"
  def wire_value(:malformed_html), do: "malformed_html"
  def wire_value(:sanitization_applied), do: "sanitization_applied"
  def wire_value(:depth_limit_exceeded), do: "depth_limit_exceeded"
end
