# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f48ced66bc592f6ed6c25ebc815b3ad04e30add2843127cd4095d46df98232be
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc """
  Whitespace handling strategy during conversion.

  Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
  """

  @typedoc "Whitespace handling strategy during conversion."
  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @doc "Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior."
  @spec normalized() :: t()
  def normalized, do: @normalized
  @doc "Preserve all whitespace exactly as it appears in the HTML."
  @spec strict() :: t()
  def strict, do: @strict

  @doc "Returns the serde wire value this variant carries on the JSON boundary (see `wire_variant_value` in alef's naming module) -- distinct from the atom's Elixir spelling."
  @spec wire_value(t()) :: String.t()
  def wire_value(:normalized), do: "Normalized"
  def wire_value(:strict), do: "Strict"
end
