# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:327c24e3cad08cf197bb1c0381f8284a3d05b4e39050a4ad48177805b31b8c93
# To regenerate: alef generate
# To verify freshness: alef verify
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc """
  Whitespace handling strategy during conversion.

  Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
  """

  @typedoc "Whitespace handling strategy during conversion."
  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @doc "Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior."
  @spec normalized() :: t()
  def normalized, do: @normalized
  @doc "Preserve all whitespace exactly as it appears in the HTML."
  @spec strict() :: t()
  def strict, do: @strict
end
