# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f15fb9a6ca964bfef00617cc14d7c0666ff49afcbd129289d079595c245029c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule HtmlToMarkdown.WhitespaceMode do
  @moduledoc """
  Whitespace handling strategy during conversion.

  Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
  """

  @typedoc "Whitespace handling strategy during conversion."
  @type t :: :normalized | :strict

  @normalized :normalized
  @strict :strict

  @doc "Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior."
  @spec normalized() :: t()
  def normalized, do: @normalized
  @doc "Preserve all whitespace exactly as it appears in the HTML."
  @spec strict() :: t()
  def strict, do: @strict
end
