<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e6640f5c9ea3b1d4b0ccaa2e44b3d52fe059c7bc245892dcd6cd6974b834142d
// To regenerate: alef generate
// To verify freshness: alef verify
declare(strict_types=1);

namespace HtmlToMarkdown;

final class HtmlToMarkdown
{
    /**
     * Convert HTML to Markdown, Djot, or plain text.
     *
     * Returns a [`ConversionResult`] with converted content plus optional metadata,
     * document structure, table data, inline images, and warnings depending on the
     * enabled features and conversion options.
     *
     * @param string $html
     * @param ?ConversionOptions $options
     * @return ConversionResult
     * @throws \HtmlToMarkdown\HtmlToMarkdownException
     */
    public static function convert(
string $html, ?ConversionOptions $options = null): ConversionResult
    {
        return \HtmlToMarkdown\HtmlToMarkdownApi::convert($html, $options); // delegate to native extension class
    }
}
