<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace HtmlToMarkdown;

final class HtmlToMarkdown
{
    /**
     * Convert HTML to Markdown, Djot, or plain text.
     *
     * Returns a [`ConversionResult`] with converted content plus optional metadata,
     * document structure, table data, inline images, and warnings depending on the
     * enabled features and conversion options.
     *
     * @param string $html
     * @param ?ConversionOptions $options
     * @return ConversionResult
     * @throws \HtmlToMarkdown\HtmlToMarkdownException
     */
    public static function convert(string $html, ?ConversionOptions $options = null): ConversionResult
    {
        return \HtmlToMarkdown\HtmlToMarkdownApi::convert($html, $options); // delegate to native extension class
    }
}
