// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:355bb05ee807e3959b9296739f2a5a238be7f48c4685d4fe80581de360ec8a77
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
