// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a1abce8ca7b1ce16ebe97a444708f64451a3ce7956e7c35ad3cb1d71651d371
// To regenerate: alef generate
// To verify freshness: alef verify
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
