// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94dd1be9921f0c99181696abdb7a25b59df4f9229ed5f05876faf9831bbba0f5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
