// Generated by alef. Do not edit by hand.
// alef:hash:f44000653901d10b61e9069d2e901a11b70b0e643ba63d75f2222729c924ae82

export 'html_to_markdown_rs_bridge_generated/lib.dart';
export 'traits.dart';
import 'html_to_markdown_rs_bridge_generated/lib.dart' as rust_bridge;
// ignore: duplicate_import
import 'html_to_markdown_rs_bridge_generated/lib.dart';

class H2mBridge {
  /// Convert HTML to Markdown, Djot, or plain text.
  ///
  /// Returns a [`ConversionResult`] with converted content plus optional metadata,
  /// document structure, table data, inline images, and warnings depending on the
  /// enabled features and conversion options.
  ///
  /// # Arguments
  ///
  /// * `html` — the HTML string to convert.
  /// * `options` — conversion options. Rust accepts bare [`ConversionOptions`],
  ///   `Some(options)`, or `None`. Language bindings expose the same option
  ///   fields through native constructors or optional parameters.
  ///
  /// # Example
  ///
  /// ```
  /// use html_to_markdown_rs::{convert, ConversionOptions};
  ///
  /// let html = "<h1>Hello World</h1>";
  ///
  /// // Bare options — most ergonomic.
  /// let result = convert(html, ConversionOptions::default()).unwrap();
  /// assert!(result.content.as_deref().unwrap_or("").contains("Hello World"));
  ///
  /// // `None` falls back to defaults.
  /// let result = convert(html, None).unwrap();
  /// assert!(result.content.as_deref().unwrap_or("").contains("Hello World"));
  /// ```
  ///
  /// # Errors
  ///
  /// Returns an error if HTML parsing fails or if the input contains invalid UTF-8.
  ///
  /// # Observability
  ///
  /// Emits an `html_to_markdown::convert` span at `INFO` level with fields `input_len`,
  /// `output_format`, `wrap`, `extract_metadata`, `extract_images`, and `tier_strategy`. These
  /// field names are part of the public observability contract and are kept stable across
  /// releases. This crate never installs a `tracing` subscriber — attach one in the consuming
  /// application to observe these spans and events.
  /// throws ConversionError on failure
  static Future<ConversionResult> convert(String html, {ConversionOptions? options}) async {
    return await rust_bridge.convert(html: html, options: options);
  }

}
