<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f15fb9a6ca964bfef00617cc14d7c0666ff49afcbd129289d079595c245029c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);

// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../packages/php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
