<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c5ac32d458f57ca6c8b3b501d81a14b91ad3a6eaf3c62ab6c7f85998db706792
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);

// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../crates/html-to-markdown-php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
