//! Ownership regression test for numeric handles returned by
//! `htm_conversion_options_visitor`.
//!
//! `htm_conversion_options_visitor` (crates/html-to-markdown-ffi/src/lib.rs, generated by
//! Alef) returns an owned numeric handle that the caller must release with
//! `htm_visitor_handle_free`. Repeated getter calls must register independent handles so each
//! can be freed exactly once without invalidating the options allocation or the other handle.

#![cfg(feature = "visitor")]
#![allow(unsafe_code)]

use std::ffi::{c_char, c_void};

use html_to_markdown_ffi::*;

const INVALID_HANDLE: u64 = 0;

#[allow(clippy::missing_const_for_fn)]
unsafe extern "C" fn noop_visit_text(
    _ctx: *const HtmContext,
    _user_data: *mut c_void,
    _text: *const c_char,
    _out_custom: *mut *mut c_char,
    _out_len: *mut usize,
) -> i32 {
    0 // HTM_VISIT_CONTINUE
}

/// SAFETY: see `ffi_panic_boundary_test::empty_callbacks` — an all-zero `HtmVisitorCallbacks`
/// is a valid "every callback is `None`" value.
#[allow(clippy::missing_const_for_fn)]
unsafe fn empty_callbacks() -> HtmVisitorCallbacks {
    unsafe { std::mem::zeroed() }
}

#[test]
fn should_return_independently_owned_handles_on_repeated_visitor_getter_calls() {
    unsafe {
        let mut callbacks = empty_callbacks();
        callbacks.visit_text = Some(noop_visit_text);
        let visitor = htm_visitor_create(&raw const callbacks);
        assert_ne!(visitor, INVALID_HANDLE);

        let options = htm_conversion_options_default();
        assert_ne!(options, INVALID_HANDLE);
        htm_options_set_visitor(options, visitor);

        let first = htm_conversion_options_visitor(options);
        let second = htm_conversion_options_visitor(options);
        assert_ne!(first, INVALID_HANDLE);
        assert_ne!(second, INVALID_HANDLE);

        assert_ne!(
            first, second,
            "htm_conversion_options_visitor must register a fresh owned handle on each call"
        );

        htm_visitor_handle_free(first);
        htm_visitor_handle_free(second);
        htm_visitor_free(visitor);
        htm_conversion_options_free(options);
    }
}
