// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:411256ebae58a5a5ab1b77fe1f91fe158a88eecdc7709575c93a6e4ed499f324
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
