// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:49e6d0f2610688d15eafa6bccd0163ba42ba035de6f9fea6a32f1c39c0f2814f
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
