// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5ebe83379af8a56c8222bf5da83d04ae572ac267405982f06b4f7468d0868795
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid configuration
/// </summary>
public class ConfigErrorException : ConversionErrorException
{
    public ConfigErrorException(string message) : base(message) { }

    public ConfigErrorException(string message, Exception innerException) : base(message, innerException) { }
}
