// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:aff1fb6a41198ba936446c1d39dc1abf10cc3a3e9adfd5d483552b6c011e752f
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
