// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ab9f376bc351fb6cd526e018d4f7792ff9ac859d9ab556b49b26434591a3fb39
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Errors that can occur during HTML to Markdown conversion.
/// </summary>
public class ConversionErrorException : HtmlToMarkdownRsException
{
    public ConversionErrorException(string message) : base(message) { }

    public ConversionErrorException(string message, Exception innerException) : base(message, innerException) { }
}
