// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b49faaf77fb74e29e6a1721e807cacb54f9b71644b5583732a78cc9126fb68e0
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Heading style options for Markdown output.
///
/// Controls how headings (h1-h6) are rendered in the output Markdown.
/// </summary>
[JsonConverter(typeof(HeadingStyleJsonConverter))]
public enum HeadingStyle
{
    /// <summary>
    /// Underlined style (=== for h1, --- for h2).
    /// </summary>
    [JsonPropertyName("Underlined")]
    Underlined,
    /// <summary>
    /// ATX style (# for h1, ## for h2, etc.). Default.
    /// </summary>
    [JsonPropertyName("Atx")]
    Atx,
    /// <summary>
    /// ATX closed style (# title #, with closing hashes).
    /// </summary>
    [JsonPropertyName("AtxClosed")]
    AtxClosed,
}


/// <summary>
/// Custom JSON converter for <see cref="HeadingStyle"/> that respects explicit variant names.
/// </summary>
internal sealed class HeadingStyleJsonConverter : JsonConverter<HeadingStyle>
{
    public override HeadingStyle Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Underlined" => HeadingStyle.Underlined,
            "Atx" => HeadingStyle.Atx,
            "AtxClosed" => HeadingStyle.AtxClosed,
            _ => throw new JsonException($"Unknown HeadingStyle value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, HeadingStyle value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            HeadingStyle.Underlined => "Underlined",
            HeadingStyle.Atx => "Atx",
            HeadingStyle.AtxClosed => "AtxClosed",
            _ => throw new JsonException($"Unknown HeadingStyle value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
