// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bd4bd79ab3f53bd5d1bff5e6b7fe582c03e7b33a64a54a5ada5e4960a36a32d5
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }

    public HtmlToMarkdownRsException(string message) : base(message)
    {
        Code = 0;
    }

    public HtmlToMarkdownRsException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
