// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:411256ebae58a5a5ab1b77fe1f91fe158a88eecdc7709575c93a6e4ed499f324
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }

    public HtmlToMarkdownRsException(string message) : base(message)
    {
        Code = 0;
    }

    public HtmlToMarkdownRsException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
