// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5409d7634f4b35a172ded09a6ff4426687af9fa83d45150cd3e6ea4eea8cdbcc
#nullable enable

using System;

namespace HtmlToMarkdown;

public class HtmlToMarkdownRsException : Exception
{
    public int Code { get; }

    public HtmlToMarkdownRsException(int code, string message) : base(message)
    {
        Code = code;
    }

    public HtmlToMarkdownRsException(string message) : base(message)
    {
        Code = 0;
    }

    public HtmlToMarkdownRsException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
