// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0fd0e8d3afb39b67c07e358090f5cff824d85428657f0d83a90f5a1de085c290
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Image source classification for proper handling and processing.
///
/// Determines whether an image is embedded (data URI), inline SVG, external, or relative.
/// </summary>
[JsonConverter(typeof(ImageTypeJsonConverter))]
public enum ImageType
{
    /// <summary>
    /// Data URI embedded image (base64 or other encoding)
    /// </summary>
    [JsonPropertyName("data_uri")]
    DataUri,
    /// <summary>
    /// Inline SVG element
    /// </summary>
    [JsonPropertyName("inline_svg")]
    InlineSvg,
    /// <summary>
    /// External image URL (http/https)
    /// </summary>
    [JsonPropertyName("external")]
    External,
    /// <summary>
    /// Relative image path
    /// </summary>
    [JsonPropertyName("relative")]
    Relative,
}


/// <summary>
/// Custom JSON converter for <see cref="ImageType"/> that respects explicit variant names.
/// </summary>
internal sealed class ImageTypeJsonConverter : JsonConverter<ImageType>
{
    public override ImageType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "data_uri" => ImageType.DataUri,
            "inline_svg" => ImageType.InlineSvg,
            "external" => ImageType.External,
            "relative" => ImageType.Relative,
            _ => throw new JsonException($"Unknown ImageType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ImageType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ImageType.DataUri => "data_uri",
            ImageType.InlineSvg => "inline_svg",
            ImageType.External => "external",
            ImageType.Relative => "relative",
            _ => throw new JsonException($"Unknown ImageType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
