// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:18a87308b03c6506394f5d4db8bf30f101874571801bb40e6654c4f6df3fe93c
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
