// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:11b53512ce352fa429b3487113320a2a4a72d302f7a5f4f2ceda41991f6d1847
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Invalid input data
/// </summary>
public class InvalidInputException : ConversionErrorException {
  public InvalidInputException(string message) : base(message) {}

  public InvalidInputException(string message, Exception innerException)
      : base(message, innerException) {}
}
