// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:80a0de8dcb124ecb0b55fe77a99e8b26cb3d9e200700f0a1d6cf0c0a54bd2b48
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
