// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:11b53512ce352fa429b3487113320a2a4a72d302f7a5f4f2ceda41991f6d1847
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException {
  public IoErrorException(string message) : base(message) {}

  public IoErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
