// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e93119435f55d0287b4d58c285db7c5fb0cbbf6e64dafc97914122325fbf3810
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// I/O error — stores the error message string so the variant is FFI-safe.
///
/// Use `ConversionError.from(io_error)` to convert from `std.io.Error`.
/// </summary>
public class IoErrorException : ConversionErrorException
{
    public IoErrorException(string message) : base(message) { }

    public IoErrorException(string message, Exception innerException) : base(message, innerException) { }
}
