// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:61a867d088f2d0dac612ae1c21238c6a4cb4cd3ea522bd80775fc8e1f9badc70
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System.Collections.Generic;
using System.Text.Json;

namespace HtmlToMarkdown;

/// <summary>
/// Utility for lenient JSON deserialization that ignores unknown properties.
/// </summary>
internal static class JsonLeniency
{
    /// <summary>
    /// Remove unknown properties from a JSON object before deserialization, so JSON
    /// carrying extra fields still parses into a type that does not declare them.
    /// </summary>
    /// <param name="json">The JSON string to filter.</param>
    /// <param name="knownProperties">Set of property names that are known/allowed.</param>
    /// <returns>A JSON string with unknown properties removed.</returns>
    public static string FilterUnknownProperties(string json, HashSet<string> knownProperties)
    {
        if (string.IsNullOrEmpty(json) || json.Trim() == "{}" || json.Trim() == "[]" || json.Trim() == "null")
        {
            return json;
        }

        try
        {
            using var document = JsonDocument.Parse(json);
            if (document.RootElement.ValueKind != JsonValueKind.Object)
            {
                return json;
            }

            using var stream = new System.IO.MemoryStream();
            using var writer = new Utf8JsonWriter(stream);

            writer.WriteStartObject();
            foreach (var property in document.RootElement.EnumerateObject())
            {
                if (knownProperties.Contains(property.Name))
                {
                    writer.WritePropertyName(property.Name);
                    property.Value.WriteTo(writer);
                }
            }
            writer.WriteEndObject();
            writer.Flush();

            return System.Text.Encoding.UTF8.GetString(stream.ToArray());
        }
        catch
        {
            // If filtering fails, return the original JSON and let deserialization handle it.
            return json;
        }
    }
}
