// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// List indentation character type.
///
/// Controls whether list items are indented with spaces or tabs.
/// </summary>
[JsonConverter(typeof(ListIndentTypeJsonConverter))]
public enum ListIndentType {
  /// <summary>
  /// Use spaces for indentation. Default. Width controlled by
  /// `list_indent_width`.
  /// </summary>
  [JsonPropertyName("Spaces")] Spaces,
  /// <summary>
  /// Use tabs for indentation.
  /// </summary>
  [JsonPropertyName("Tabs")] Tabs,
}

/// <summary>
/// Custom JSON converter for <see cref="ListIndentType"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class ListIndentTypeJsonConverter
    : JsonConverter<ListIndentType> {
  public override ListIndentType Read(ref Utf8JsonReader reader,
                                      Type typeToConvert,
                                      JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch {
      "Spaces" => ListIndentType.Spaces, "Tabs" => ListIndentType.Tabs,
      _ => throw new JsonException($"Unknown ListIndentType value: {value}")
    };
  }

  public override void Write(Utf8JsonWriter writer, ListIndentType value,
                             JsonSerializerOptions options) {
    var str = value switch {
      ListIndentType.Spaces => "Spaces", ListIndentType.Tabs => "Tabs",
      _ => throw new JsonException($"Unknown ListIndentType value: {value}")
    };
    writer.WriteStringValue(str);
  }
}
