// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e9bfc384ecad7a3c8aa6a50be759de058d938d9c8053be98bf7116c2598aea36
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// List indentation character type.
///
/// Controls whether list items are indented with spaces or tabs.
/// </summary>
[JsonConverter(typeof(ListIndentTypeJsonConverter))]
public enum ListIndentType
{
    /// <summary>
    /// Use spaces for indentation. Default. Width controlled by `list_indent_width`.
    /// </summary>
    [JsonPropertyName("Spaces")]
    Spaces,
    /// <summary>
    /// Use tabs for indentation.
    /// </summary>
    [JsonPropertyName("Tabs")]
    Tabs,
}


/// <summary>
/// Custom JSON converter for <see cref="ListIndentType"/> that respects explicit variant names.
/// </summary>
internal sealed class ListIndentTypeJsonConverter : JsonConverter<ListIndentType>
{
    public override ListIndentType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Spaces" => ListIndentType.Spaces,
            "Tabs" => ListIndentType.Tabs,
            _ => throw new JsonException($"Unknown ListIndentType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ListIndentType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ListIndentType.Spaces => "Spaces",
            ListIndentType.Tabs => "Tabs",
            _ => throw new JsonException($"Unknown ListIndentType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
