// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6f9ba804d2765aa7e3825e56dcf9805b83d0d434075cd83c8c8ff6bafb0c71d2
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>
/// A single key-value metadata entry from `&lt;head&gt;` meta tags.
///
/// Binding-safe replacement for `(String, String)` tuples used in
/// `NodeContent.MetadataBlock`. Tuple pairs cannot be represented
/// across language boundaries without lossy degradation.
/// </summary>
public sealed record MetadataEntry
{
    /// <summary>
    /// Metadata key (e.g. `"title"`, `"description"`, `"og:title"`).
    /// </summary>
    [JsonPropertyName("key")]
    public required string Key { get; init; }

    /// <summary>
    /// Metadata value.
    /// </summary>
    [JsonPropertyName("value")]
    public required string Value { get; init; }


    /// <summary>
    /// Parse a <see cref="MetadataEntry"/> from a JSON string.
    /// </summary>
    /// <exception cref="HtmlToMarkdownRsException">When the JSON cannot be deserialised.</exception>
    public static MetadataEntry FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<MetadataEntry>(json, JsonOptions)
                ?? throw new HtmlToMarkdownRsException($"Failed to parse MetadataEntry from JSON: deserializer returned null");
        }
        catch (HtmlToMarkdownRsException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new HtmlToMarkdownRsException($"Failed to parse MetadataEntry from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower), new ByteArrayJsonConverter() },
    };
}
