// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f02fe676375dfabf298ae6e39febfee9084a281ebb75e77ebe6b0d6a6aa3882f
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>Context passed to every visitor callback.</summary>
public record NodeContext(
    [property: JsonPropertyName("node_type")] NodeType NodeType,
    [property: JsonPropertyName("tag_name")] string TagName,
    [property: JsonPropertyName("depth")] ulong Depth,
    [property: JsonPropertyName("index_in_parent")] ulong IndexInParent,
    [property: JsonPropertyName("parent_tag")] string? ParentTag,
    [property: JsonPropertyName("is_inline")] bool IsInline
);
