// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>Context passed to every visitor callback.</summary>
public record NodeContext(
    [property : JsonPropertyName("node_type")] NodeType NodeType,
    [property : JsonPropertyName("tag_name")] string TagName,
    [property : JsonPropertyName("depth")] ulong Depth,
    [property : JsonPropertyName("index_in_parent")] ulong IndexInParent,
    [property : JsonPropertyName("parent_tag")] string? ParentTag,
    [property : JsonPropertyName("is_inline")] bool IsInline);
