// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8a44ffd37ed9bb63a05d55c4941fa797a5ff942190b276c314be687d53463f97
// To regenerate: alef generate
// To verify freshness: alef verify
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;

/// <summary>Context passed to every visitor callback.</summary>
public record NodeContext(
    [property: JsonPropertyName("node_type")] NodeType NodeType,
    [property: JsonPropertyName("tag_name")] string TagName,
    [property: JsonPropertyName("depth")] ulong Depth,
    [property: JsonPropertyName("index_in_parent")] ulong IndexInParent,
    [property: JsonPropertyName("parent_tag")] string? ParentTag,
    [property: JsonPropertyName("is_inline")] bool IsInline
);
