// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:461918fa2a1559be4cac08c8aebec3d54a583748fedd43a953a4d5ca7de0eb14
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
