// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
