// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Generic conversion error
/// </summary>
public class OtherException : ConversionErrorException {
  public OtherException(string message) : base(message) {}

  public OtherException(string message, Exception innerException)
      : base(message, innerException) {}
}
