// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException {
  public PanicException(string message) : base(message) {}

  public PanicException(string message, Exception innerException)
      : base(message, innerException) {}
}
