// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException
{
    public PanicException(string message) : base(message) { }

    public PanicException(string message, Exception innerException) : base(message, innerException) { }
}
