// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5f15fb9a6ca964bfef00617cc14d7c0666ff49afcbd129289d079595c245029c
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// Panic caught during conversion to prevent unwinding across FFI boundaries
/// </summary>
public class PanicException : ConversionErrorException {
  public PanicException(string message) : base(message) {}

  public PanicException(string message, Exception innerException)
      : base(message, innerException) {}
}
