// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:dc9d8c1d94160871d06c41e8fba8461a430d7e634c1f9bbdc3e3fbd7b4931dff
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
