// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3263568b2a0009468eeaecfad2425b314b594dcc9bd3f8fde7b8eca760490908
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException
{
    public ParseErrorException(string message) : base(message) { }

    public ParseErrorException(string message, Exception innerException) : base(message, innerException) { }
}
