// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9fe2f7328e5ff759a03fb0c68b0bd7281cbe14bbf83d07480cf79d29af39167b
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML parsing error
/// </summary>
public class ParseErrorException : ConversionErrorException {
  public ParseErrorException(string message) : base(message) {}

  public ParseErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
