// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// HTML preprocessing aggressiveness level.
///
/// Controls the extent of cleanup performed before conversion. Higher levels
/// remove more elements.
/// </summary>
[JsonConverter(typeof(PreprocessingPresetJsonConverter))]
public enum PreprocessingPreset {
  /// <summary>
  /// Minimal cleanup. Remove only essential noise (scripts, styles).
  /// </summary>
  [JsonPropertyName("Minimal")] Minimal,
  /// <summary>
  /// Standard cleanup. Default. Removes navigation, forms, and other auxiliary
  /// content.
  /// </summary>
  [JsonPropertyName("Standard")] Standard,
  /// <summary>
  /// Aggressive cleanup. Remove extensive non-content elements and structure.
  /// </summary>
  [JsonPropertyName("Aggressive")] Aggressive,
}

/// <summary>
/// Custom JSON converter for <see cref="PreprocessingPreset"/> that respects
/// explicit variant names.
/// </summary>
internal sealed class PreprocessingPresetJsonConverter
    : JsonConverter<PreprocessingPreset> {
  public override PreprocessingPreset Read(ref Utf8JsonReader reader,
                                           Type typeToConvert,
                                           JsonSerializerOptions options) {
    var value = reader.GetString();
    return value switch { "Minimal" => PreprocessingPreset.Minimal,
                          "Standard" => PreprocessingPreset.Standard,
                          "Aggressive" => PreprocessingPreset.Aggressive,
                          _ => throw new JsonException(
                              $"Unknown PreprocessingPreset value: {value}") };
  }

  public override void Write(Utf8JsonWriter writer, PreprocessingPreset value,
                             JsonSerializerOptions options) {
    var str =
        value switch { PreprocessingPreset.Minimal => "Minimal",
                       PreprocessingPreset.Standard => "Standard",
                       PreprocessingPreset.Aggressive => "Aggressive",
                       _ => throw new JsonException(
                           $"Unknown PreprocessingPreset value: {value}") };
    writer.WriteStringValue(str);
  }
}
