// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f0f83a7f0ec95e9fa6c14023596214a907e0d582a13cd8979fb46cd5f72db15c
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException {
  public SanitizationErrorException(string message) : base(message) {}

  public SanitizationErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
