// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b4f50a89b244fa93f9d7ec25b092b0aca90f3ebacd05d24494c8309f3dd702d1
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException {
  public SanitizationErrorException(string message) : base(message) {}

  public SanitizationErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
