// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d1c2b63e5775221e809b97d66baa86414a3ea83fa84aae0c567155d51f172b89
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>
/// HTML sanitization error
/// </summary>
public class SanitizationErrorException : ConversionErrorException
{
    public SanitizationErrorException(string message) : base(message) { }

    public SanitizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
