// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d40557628153118fc9e30c312b100bf7d310b40ec42d6aa4d2b1d8396786784a
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace HtmlToMarkdown;

internal sealed class VisitorHandleSafeHandle : SafeHandle {
  internal VisitorHandleSafeHandle(IntPtr handle) : base(IntPtr.Zero, true) {
    SetHandle(handle);
  }

  public override bool IsInvalid => handle == IntPtr.Zero;

  protected override bool ReleaseHandle() {
    NativeMethods.VisitorHandleFree(handle);
    return true;
  }
}
/// <summary>/// Shareable, thread-safe handle to a user-provided HTML visitor
/// implementation./// /// Pass an instance wrapped in this handle to
/// `ConversionOptions` to/// customise how the HTML document is traversed and
/// converted to Markdown./// The handle may be cloned and shared across threads
/// without additional/// synchronisation on the caller's side./// </summary>
public sealed class VisitorHandle : IDisposable {
  private readonly VisitorHandleSafeHandle _safeHandle;

  internal VisitorHandle(IntPtr handle) {
    _safeHandle = new VisitorHandleSafeHandle(handle);
  }

  internal IntPtr Handle => _safeHandle.DangerousGetHandle();

  public void Dispose() => _safeHandle.Dispose();
}
