// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:94dd1be9921f0c99181696abdb7a25b59df4f9229ed5f05876faf9831bbba0f5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>Controls how the visitor affects the conversion pipeline.</summary>
public abstract record VisitResult {
  private VisitResult() {}

  public sealed record Continue : VisitResult;

  public sealed record Skip : VisitResult;

  public sealed record PreserveHtml : VisitResult;

  public sealed record Custom(string Value) : VisitResult;

  public sealed record Error(string Value) : VisitResult;

  internal string ToFfiJson() => this switch {
    VisitResult.Continue => "\"Continue\"",
    VisitResult.Skip => "\"Skip\"",
    VisitResult.PreserveHtml => "\"PreserveHtml\"",
    VisitResult.Custom c =>
        "{\"Custom\":" + System.Text.Json.JsonSerializer.Serialize(c.Value) +
        "}",
    VisitResult.Error c =>
        "{\"Error\":" + System.Text.Json.JsonSerializer.Serialize(c.Value) +
        "}",
    _ => "\"Continue\""
  };
}
