// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;

namespace HtmlToMarkdown;

/// <summary>Controls how the visitor affects the conversion pipeline.</summary>
public abstract record VisitResult {
  private VisitResult() {}

  public sealed record Continue : VisitResult;

  public sealed record Skip : VisitResult;

  public sealed record PreserveHtml : VisitResult;

  public sealed record Custom(string Value) : VisitResult;

  public sealed record Error(string Value) : VisitResult;

  internal string ToFfiJson() => this switch {
    VisitResult.Continue => "\"Continue\"",
    VisitResult.Skip => "\"Skip\"",
    VisitResult.PreserveHtml => "\"PreserveHtml\"",
    VisitResult.Custom c =>
        "{\"Custom\":" + System.Text.Json.JsonSerializer.Serialize(c.Value) +
        "}",
    VisitResult.Error c =>
        "{\"Error\":" + System.Text.Json.JsonSerializer.Serialize(c.Value) +
        "}",
    _ => "\"Continue\""
  };
}
