// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8d434f358315de40a5ac1cdcd1cc1f68dce0ac124c5f720af3022ebbb61d6851
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HtmlToMarkdown;
/// <summary>
/// Whitespace handling strategy during conversion.
///
/// Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
/// </summary>
[JsonConverter(typeof(WhitespaceModeJsonConverter))]
public enum WhitespaceMode
{
    /// <summary>
    /// Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
    /// </summary>
    [JsonPropertyName("Normalized")]
    Normalized,
    /// <summary>
    /// Preserve all whitespace exactly as it appears in the HTML.
    /// </summary>
    [JsonPropertyName("Strict")]
    Strict,
}


/// <summary>
/// Custom JSON converter for <see cref="WhitespaceMode"/> that respects explicit variant names.
/// </summary>
internal sealed class WhitespaceModeJsonConverter : JsonConverter<WhitespaceMode>
{
    public override WhitespaceMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Normalized" => WhitespaceMode.Normalized,
            "Strict" => WhitespaceMode.Strict,
            _ => throw new JsonException($"Unknown WhitespaceMode value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, WhitespaceMode value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            WhitespaceMode.Normalized => "Normalized",
            WhitespaceMode.Strict => "Strict",
            _ => throw new JsonException($"Unknown WhitespaceMode value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
