# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed4b359577c60e49d179f2ada11b3e7c123f74c5b045685336184c80dbc4c2b6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Exception hierarchy (re-exported from the native module)."""

from ._html_to_markdown import (
    ConfigError,
    ConversionError,
    InvalidInputError,
    IoError,
    OtherError,
    PanicError,
    ParseError,
    SanitizationError,
)

__all__ = [
    "ConfigError",
    "ConversionError",
    "InvalidInputError",
    "IoError",
    "OtherError",
    "PanicError",
    "ParseError",
    "SanitizationError",
]

# Re-point each exception's __module__ at the public package so tracebacks show the
# public name (e.g. "DownloadError"), not the native module name (GitHub issue #147).
_public_module = __name__.rsplit(".", 1)[0]
for _name in __all__:
    globals()[_name].__module__ = _public_module
del _name, _public_module
