# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL
