# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b8a42bb668160a874ba134bff557118848528c38ab75293060ddec09648d4ce
# To regenerate: alef generate
# To verify freshness: alef verify

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL
