# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b29145cdf8b535272542b22e74fa127d508fe6b6b10f53600ce7e16d511c6a4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code

#' @useDynLib htmltomarkdown, .registration = TRUE
NULL
