# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b319aa67929cdf1f74a7d178a77b3d830b8d2eae2e3081f18f260914092be1f
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

require 'html_to_markdown'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_empty_string: Empty string produces empty output' do
    result = HtmlToMarkdown.convert('')
    expect(result.content.to_s).to eq('')

  end

  it 'smoke_simple_heading: H1 heading converts to ATX markdown' do
    result = HtmlToMarkdown.convert('<h1>Title</h1>')
    expect(result.content.to_s).to include('# Title')

  end

  it 'smoke_simple_paragraph: Simple paragraph converts correctly' do
    result = HtmlToMarkdown.convert('<p>Hello World</p>')
    expect(result.content.to_s).to eq('Hello World')
    expect(result.content.respond_to?(:empty?) ? !result.content.empty? : !result.content.nil?).to be(true)

  end
end
