// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b49faaf77fb74e29e6a1721e807cacb54f9b71644b5583732a78cc9126fb68e0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.htmltomarkdown.HtmlToMarkdownRs;
import io.xberg.htmltomarkdown.ConversionOptions;
import java.util.Optional;
import io.xberg.htmltomarkdown.JsonUtil;

/** E2e tests for category: smoke. */
public class SmokeTest {

    @Test
    void testSmokeEmptyString() throws Exception {
        // Empty string produces empty output
        var result = HtmlToMarkdownRs.convert("", ConversionOptions.builder().build());
assertEquals("", java.util.Optional.ofNullable(result.content()).map(java.util.Objects::toString).orElse("").trim());

    }


    @Test
    void testSmokeSimpleHeading() throws Exception {
        // H1 heading converts to ATX markdown
        var result = HtmlToMarkdownRs.convert("<h1>Title</h1>", ConversionOptions.builder().build());
assertTrue(java.util.Optional.ofNullable(result.content()).map(java.util.Objects::toString).orElse("").contains("# Title"), "expected to contain: " + "# Title");

    }


    @Test
    void testSmokeSimpleParagraph() throws Exception {
        // Simple paragraph converts correctly
        var result = HtmlToMarkdownRs.convert("<p>Hello World</p>", ConversionOptions.builder().build());
assertEquals("Hello World", java.util.Optional.ofNullable(result.content()).map(java.util.Objects::toString).orElse("").trim());assertFalse(java.util.Optional.ofNullable(result.content()).isEmpty(), "expected non-empty value");

    }

}
