/*
 * This file is auto-generated by alef — DO NOT EDIT.
 * alef:hash:81ce7477531ed66bf6f1d4d10108545f47918fc8308edb1bf5b2a46e5280813c
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 */
/* E2e tests for category: edge-cases */

#include <assert.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "html_to_markdown.h"
#include "test_runner.h"

void test_empty_html(void) {
    /* Empty HTML document */
    HTMConversionResult* result = htm_convert("<html><head></head><body></body></html>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(str_trim_eq(content, "") == 0 && "equals assertion failed");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_encoding_cjk_characters(void) {
    /* CJK (Chinese, Japanese, Korean) characters are preserved */
    HTMConversionResult* result = htm_convert("<p>中文内容</p><p>日本語テキスト</p><p>한국어 텍스트</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "中文内容") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "日本語テキスト") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "한국어 텍스트") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_encoding_html_entities(void) {
    /* Common HTML entities are decoded in output */
    HTMConversionResult* result = htm_convert("<p>&amp; &lt; &gt; &nbsp; &quot; &apos;</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "&") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "<") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, ">") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_encoding_named_entities(void) {
    /* Named HTML entities like &mdash; and &hellip; are decoded */
    HTMConversionResult* result = htm_convert("<p>Em dash&mdash;used for parenthetical remarks&mdash;is common. Ellipsis&hellip; indicates omission. Non-breaking&nbsp;space.</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "—") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "…") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_encoding_numeric_entities(void) {
    /* Numeric HTML entities (decimal and hex) are decoded */
    HTMConversionResult* result = htm_convert("<p>Copyright: &#169; Trade: &#174; Euro: &#8364; Hex: &#x00A9;</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "©") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "®") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "€") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_encoding_unicode_emoji(void) {
    /* Emoji and Unicode characters are preserved */
    HTMConversionResult* result = htm_convert("<p>Hello 🌍 World 🚀</p><p>Stars: ⭐ ✨</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "🌍") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "🚀") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "⭐") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_hidden_content_aria_hidden_still_rendered(void) {
    /* aria-hidden only hides content from assistive tech, not visually — it must still be rendered */
    HTMConversionResult* result = htm_convert("<p>visible</p><div aria-hidden=\"true\">still shown</div><p>also visible</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strstr(content, "visible") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "still shown") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "also visible") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_hidden_content_display_none_dropped(void) {
    /* Elements hidden via inline style="display:none" must not appear in the output */
    HTMConversionResult* result = htm_convert("<p>visible</p><div style=\"display:none\">secret hidden text</div><p>also visible</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert((content == NULL || strstr(content, "secret hidden text") == NULL) && "expected NOT to contain substring");
    assert(content != NULL && strstr(content, "visible") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "also visible") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_hidden_content_noscript_element_dropped(void) {
    /* Content inside <noscript> only renders with scripting disabled and must not appear in the output */
    HTMConversionResult* result = htm_convert("<p>visible</p><noscript><p>secret noscript text</p></noscript><p>also visible</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert((content == NULL || strstr(content, "secret noscript text") == NULL) && "expected NOT to contain substring");
    assert(content != NULL && strstr(content, "visible") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "also visible") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_hidden_content_template_element_dropped(void) {
    /* Content inside <template> is never rendered per the HTML spec and must not appear in the output */
    HTMConversionResult* result = htm_convert("<p>visible</p><template><p>secret template text</p></template><p>also visible</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert((content == NULL || strstr(content, "secret template text") == NULL) && "expected NOT to contain substring");
    assert(content != NULL && strstr(content, "visible") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "also visible") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_hidden_content_visibility_hidden_dropped(void) {
    /* Elements hidden via inline style="visibility:hidden" must not appear in the output */
    HTMConversionResult* result = htm_convert("<p>visible</p><span style=\"visibility:hidden\">secret hidden span</span><p>also visible</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert((content == NULL || strstr(content, "secret hidden span") == NULL) && "expected NOT to contain substring");
    assert(content != NULL && strstr(content, "visible") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "also visible") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_html_comments_only(void) {
    /* Document containing only HTML comments produces empty output */
    HTMConversionResult* result = htm_convert("<!-- This is a comment --><!-- Another comment -->", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(str_trim_eq(content, "") == 0 && "equals assertion failed");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_just_whitespace_input(void) {
    /* Input that is only whitespace characters (spaces, tabs, newlines) produces empty output */
    HTMConversionResult* result = htm_convert("   ", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(str_trim_eq(content, "") == 0 && "equals assertion failed");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_malformed_bogus_comment_triple_dash(void) {
    /* HTML comment ending with ---> (three dashes) must not drop content that follows (issue #339) */
    HTMConversionResult* result = htm_convert("<h1>One</h1>\n<!-- /// --->\n<p>Two</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strstr(content, "One") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "Two") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_malformed_deeply_nested_elements(void) {
    /* Deeply nested elements (100 levels) are handled without stack overflow */
    HTMConversionResult* result = htm_convert("<div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><div><p>Deeply nested content</p></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "Deeply nested content") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_malformed_missing_block_closing_tags(void) {
    /* Missing closing tags on block elements are auto-closed by parser */
    HTMConversionResult* result = htm_convert("<div><h1>Title<p>First paragraph<p>Second paragraph</div>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "Title") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "First paragraph") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "Second paragraph") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_malformed_overlapping_tags(void) {
    /* Overlapping bold/italic tags are recovered by the HTML parser without panic */
    HTMConversionResult* result = htm_convert("<p><b><i>bold and italic</b></i></p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "bold and italic") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_malformed_unclosed_paragraph(void) {
    /* Unclosed <p> tag is recovered gracefully and content is preserved */
    HTMConversionResult* result = htm_convert("<p>This paragraph is never closed", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "This paragraph is never closed") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_script_tags_only(void) {
    /* Document with only script tags produces empty output (scripts are stripped) */
    HTMConversionResult* result = htm_convert("<html><head><script>alert('xss')</script></head><body><script>document.write('hello')</script></body></html>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(str_trim_eq(content, "") == 0 && "equals assertion failed");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_style_tags_only(void) {
    /* Document with only style tags produces empty output (styles are stripped) */
    HTMConversionResult* result = htm_convert("<html><head><style>body { color: red; }</style></head><body><style>.foo { margin: 0; }</style></body></html>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(str_trim_eq(content, "") == 0 && "equals assertion failed");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_whitespace_only(void) {
    /* Whitespace-only content */
    HTMConversionResult* result = htm_convert("<p>   </p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(str_trim_eq(content, "") == 0 && "equals assertion failed");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_xss_onclick_handler_removed(void) {
    /* onclick and other on* event handlers are removed from elements */
    HTMConversionResult* result = htm_convert("<p><a href=\"https://example.com\" onclick=\"alert('xss')\">Click me</a></p><button onmouseover=\"steal_data()\">Hover me</button>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "Click me") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_xss_script_tag_stripped(void) {
    /* Script tag content is stripped and does not appear in output */
    HTMConversionResult* result = htm_convert("<p>Safe content.</p><script>alert('xss')</script><p>More safe content.</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "Safe content") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "More safe content") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}

void test_xss_svg_nested_script_stripped(void) {
    /* Script tags nested inside SVG are stripped */
    HTMConversionResult* result = htm_convert("<p>Before SVG.</p><svg xmlns=\"http://www.w3.org/2000/svg\"><script>alert('svg-xss')</script><text>SVG text</text></svg><p>After SVG.</p>", NULL);
    assert(result != NULL && "expected call to succeed");
    char* content = htm_conversion_result_content(result);
    assert(content != NULL && strlen(content) > 0 && "expected non-empty value");
    assert(content != NULL && strstr(content, "Before SVG") != NULL && "expected to contain substring");
    assert(content != NULL && strstr(content, "After SVG") != NULL && "expected to contain substring");
    htm_free_string(content);
    htm_conversion_result_free(result);
}
