// Generated by alef. Do not edit by hand.
// alef:hash:8d115ad995656db6ec437e434ec942658d69d01ccdf13493bc6ba66f7ec39b71
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/** Errors that can occur during HTML to Markdown conversion. */
sealed class ConversionError(message: String) : Exception(message) {
    data class ParseError(val field0: String) : ConversionError("HTML parsing error: $field0")
    data class SanitizationError(
        val field0: String,
    ) : ConversionError("Sanitization error: $field0")
    data class ConfigError(val field0: String) : ConversionError("Invalid configuration: $field0")
    data class IoError(val field0: String) : ConversionError("I/O error: $field0")
    data class Panic(val field0: String) : ConversionError("Internal panic: $field0")
    data class InvalidInput(val field0: String) : ConversionError("Invalid input: $field0")
    data class Other(val field0: String) : ConversionError("Conversion error: $field0")
}
