// Generated by alef. Do not edit by hand.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
 * The primary result of HTML conversion and extraction.
 *
 * Contains the converted text output, optional structured document tree,
 * metadata, extracted tables, images, and processing warnings.
 */
data class ConversionResult(
    /** Converted text output in the selected format: Markdown, Djot, or plain text. */
    val content: String? = null,
    /**
     * Structured document tree with semantic elements.
     *
     * Populated when the `include_document_structure` option is `true`. `null`
     * otherwise (the default), which avoids the overhead of building the tree.
     *
     * When present, the tree mirrors the converted document: headings open
     * `Group` sections, paragraphs and list items carry
     * inline `TextAnnotation`s, and tables reference the same
     * `TableGrid` data exposed in the result's `tables` field.
     *
     * Note: this field is independent of the `metadata` feature flag. Document structure
     * collection is always available at runtime; it is gated only by the runtime option, not
     * by a compile-time feature.
     */
    val document: DocumentStructure? = null,
    /** Extracted HTML metadata (title, OG, links, images, structured data). */
    val metadata: HtmlMetadata = HtmlMetadata(),
    /** Extracted tables with structured cell data and markdown representation. */
    val tables: List<TableData> = emptyList(),
    /** Non-fatal processing warnings. */
    val warnings: List<ProcessingWarning> = emptyList(),
)
