// Generated by alef. Do not edit by hand.
// alef:hash:5f15fb9a6ca964bfef00617cc14d7c0666ff49afcbd129289d079595c245029c
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/** A single cell in a table grid. */
data class GridCell(
    /** The text content of the cell. */
    val content: String,
    /** 0-indexed row position. */
    val row: Int,
    /** 0-indexed column position. */
    val col: Int,
    /** Number of rows this cell spans (default 1). */
    val rowSpan: Int,
    /** Number of columns this cell spans (default 1). */
    val colSpan: Int,
    /** Whether this is a header cell (`<th>`). */
    val isHeader: Boolean,
)
