// Generated by alef. Do not edit by hand.
// alef:hash:f0f83a7f0ec95e9fa6c14023596214a907e0d582a13cd8979fb46cd5f72db15c
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
 * Header element metadata with hierarchy tracking.
 *
 * Captures heading elements (h1-h6) with their text content, identifiers,
 * and position in the document structure.
 */
data class HeaderMetadata(
    /** Header level: 1 (h1) through 6 (h6) */
    val level: Byte,
    /** Normalized text content of the header */
    val text: String,
    /** HTML id attribute if present */
    val id: String? = null,
    /** Document tree depth at the header element */
    val depth: Long,
    /** Byte offset in original HTML document */
    val htmlOffset: Long,
) {

    fun isValid(): Boolean {
        throw UnsupportedOperationException(
            "isValid is not yet bridged via JNI; reconstruct via Builder."
        )
    }
}
