// Generated by alef. Do not edit by hand.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
* Heading style options for Markdown output.
*
* Controls how headings (h1-h6) are rendered in the output Markdown.
*/
enum class HeadingStyle {
    /** Underlined style (=== for h1, --- for h2). */
    @com.fasterxml.jackson.annotation.JsonProperty("Underlined") UNDERLINED,
    /** ATX style (# for h1, ## for h2, etc.). Default. */
    @com.fasterxml.jackson.annotation.JsonProperty("Atx") ATX,
    /** ATX closed style (# title #, with closing hashes). */
    @com.fasterxml.jackson.annotation.JsonProperty("AtxClosed") ATX_CLOSED;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        UNDERLINED -> "Underlined"
        ATX -> "Atx"
        ATX_CLOSED -> "AtxClosed"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): HeadingStyle =
        when (value) {
            "Underlined",
            "underlined" -> UNDERLINED
            "Atx",
            "atx" -> ATX
            "AtxClosed",
            "atxclosed" -> ATX_CLOSED
            else -> throw IllegalArgumentException("Unknown HeadingStyle value: $value")
        }
    }
}
