// Generated by alef. Do not edit by hand.
// alef:hash:70322700f93e66afad9c2da7380f3018c86a04bbf5aaa5b61c78a871cca180ec

package io.xberg.android

class HtmlToMarkdownRsBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
