// Generated by alef. Do not edit by hand.
// alef:hash:1f340c6014f36f585a8522fe2d428971d5f3b29a81700b0cc4f83289b4de3ee1
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package io.xberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init { System.loadLibrary("htm_jni") }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI external funs for data-class instance methods.
    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeHeaderMetadataIsValid(selfJson: String): Boolean

    // JNI trait-bridge external funs — implementations are Rust JNI shims.
}
