// Generated by alef. Do not edit by hand.
// alef:hash:16844cb234b3b4d861c9c3d6003b94a620d76988f9aa886f19d699c6ca5a4f63
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package io.xberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init { System.loadLibrary("htm_jni") }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI external funs for data-class instance methods.
    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeHeaderMetadataIsValid(selfJson: String): Boolean

    // JNI trait-bridge external funs — implementations are Rust JNI shims.
}
