// Generated by alef. Do not edit by hand.
// alef:hash:aff1fb6a41198ba936446c1d39dc1abf10cc3a3e9adfd5d483552b6c011e752f

package io.xberg.android

class HtmlToMarkdownRsBridgeException(message: String?, cause: Throwable?) : RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
