// Generated by alef. Do not edit by hand.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
@file:Suppress(
    "ktlint:standard:max-line-length",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:annotation",
    "MaxLineLength",
    "TooManyFunctions",
    "LongParameterList",
)

package io.xberg.android

@Suppress("TooManyFunctions")
object HtmlToMarkdownRsBridge {
    init { System.loadLibrary("htm_jni") }

    @Throws(HtmlToMarkdownRsBridgeException::class)
    external fun nativeConvert(html: String, options: String): String

    // JNI trait-bridge external funs — implementations are Rust JNI shims.

    // Destructor external funs for handle-only opaque types.
    external fun nativeFreeVisitorHandle(handle: Long)
}
