// Generated by alef. Do not edit by hand.
// alef:hash:48ebac1f640ea61648c92b02cd06cf9b0ec1f7466d628c9a38510f1d15fbfb21
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
 * Comprehensive metadata extraction result from HTML document.
 *
 * Contains all extracted metadata types in a single structure,
 * suitable for serialization and transmission across language boundaries.
 */
data class HtmlMetadata(
    /** Document-level metadata (title, description, canonical, etc.) */
    val document: DocumentMetadata = DocumentMetadata(),
    /** Extracted header elements with hierarchy */
    val headers: List<HeaderMetadata> = emptyList(),
    /** Extracted hyperlinks with type classification */
    val links: List<LinkMetadata> = emptyList(),
    /** Extracted images with source and dimensions */
    val images: List<ImageMetadata> = emptyList(),
    /** Extracted structured data blocks */
    val structuredData: List<StructuredData> = emptyList(),
)
