// Generated by alef. Do not edit by hand.
// alef:hash:caac0f9328c3a74123c49796724106a1e5e3a6eadd758cbad2d0eca1cb37f05a
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
* Image source classification for proper handling and processing.
*
* Determines whether an image is embedded (data URI), inline SVG, external, or relative.
*/
enum class ImageType {
    /** Data URI embedded image (base64 or other encoding) */
    @com.fasterxml.jackson.annotation.JsonProperty("data_uri") DATA_URI,
    /** Inline SVG element */
    @com.fasterxml.jackson.annotation.JsonProperty("inline_svg") INLINE_SVG,
    /** External image URL (http/https) */
    @com.fasterxml.jackson.annotation.JsonProperty("external") EXTERNAL,
    /** Relative image path */
    @com.fasterxml.jackson.annotation.JsonProperty("relative") RELATIVE;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        DATA_URI -> "data_uri"
        INLINE_SVG -> "inline_svg"
        EXTERNAL -> "external"
        RELATIVE -> "relative"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ImageType =
        when (value) {
            "data_uri" -> DATA_URI
            "inline_svg" -> INLINE_SVG
            "external" -> EXTERNAL
            "relative" -> RELATIVE
            else -> throw IllegalArgumentException("Unknown ImageType value: $value")
        }
    }
}
