// Generated by alef. Do not edit by hand.
// alef:hash:9df630bda795d1d0b5958a465ce7c5dcf81f20b6c387e9b82d68b250ef877bcb
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
 * Hyperlink metadata with categorization and attributes.
 *
 * Represents `<a>` elements with parsed href values, text content, and link type classification.
 */
data class LinkMetadata(
    /** The href URL value */
    val href: String,
    /** Link text content (normalized, concatenated if mixed with elements) */
    val text: String,
    /** Optional title attribute (often shown as tooltip) */
    val title: String? = null,
    /** Link type classification */
    val linkType: LinkType,
    /** Rel attribute values (e.g., "nofollow", "stylesheet", "canonical") */
    val rel: List<String> = emptyList(),
    /** Additional HTML attributes */
    val attributes: Map<String, String> = emptyMap(),
)
