// Generated by alef. Do not edit by hand.
// alef:hash:09fe6dd1d2fb6f1dbd6cd3340d79a591f0a567105d0ce73d9119b930da9aacd3
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
* List indentation character type.
*
* Controls whether list items are indented with spaces or tabs.
*/
enum class ListIndentType {
    /** Use spaces for indentation. Default. Width controlled by `list_indent_width`. */
    @com.fasterxml.jackson.annotation.JsonProperty("Spaces") SPACES,
    /** Use tabs for indentation. */
    @com.fasterxml.jackson.annotation.JsonProperty("Tabs") TABS;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        SPACES -> "Spaces"
        TABS -> "Tabs"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): ListIndentType =
        when (value) {
            "Spaces",
            "spaces" -> SPACES
            "Tabs",
            "tabs" -> TABS
            else -> throw IllegalArgumentException("Unknown ListIndentType value: $value")
        }
    }
}
