// Generated by alef. Do not edit by hand.
// alef:hash:1b29145cdf8b535272542b22e74fa127d508fe6b6b10f53600ce7e16d511c6a4
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
* Line break syntax in Markdown output.
*
* Controls how soft line breaks (from `<br>` or line breaks in source) are rendered.
*/
enum class NewlineStyle {
    /** Two trailing spaces at end of line. Default. Standard Markdown syntax. */
    @com.fasterxml.jackson.annotation.JsonProperty("Spaces") SPACES,
    /** Backslash at end of line. Alternative Markdown syntax. */
    @com.fasterxml.jackson.annotation.JsonProperty("Backslash") BACKSLASH;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        SPACES -> "Spaces"
        BACKSLASH -> "Backslash"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): NewlineStyle =
        when (value) {
            "Spaces",
            "spaces" -> SPACES
            "Backslash",
            "backslash" -> BACKSLASH
            else -> throw IllegalArgumentException("Unknown NewlineStyle value: $value")
        }
    }
}
