// Generated by alef. Do not edit by hand.
// alef:hash:9e875201aaa1463c15e0a241122082d3c23e810863377fbf0f9aab8c635da0e6
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/** HTML preprocessing options for document cleanup before conversion. */
data class PreprocessingOptions(
    /** Enable HTML preprocessing globally */
    val enabled: Boolean = true,
    /** Preprocessing preset level (Minimal, Standard, Aggressive) */
    val preset: PreprocessingPreset = PreprocessingPreset.STANDARD,
    /** Remove navigation elements (nav, breadcrumbs, menus, sidebars) */
    val removeNavigation: Boolean = true,
    /** Remove form elements (forms, inputs, buttons, etc.) */
    val removeForms: Boolean = true,
)
