// Generated by alef. Do not edit by hand.
// alef:hash:ae27fb2270a21feb95d12e56306ee8cb658cb16e6b0de1fb02eef725f0889bb7
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg.android

/**
* Whitespace handling strategy during conversion.
*
* Determines how sequences of whitespace characters (spaces, tabs, newlines) are processed.
*/
enum class WhitespaceMode {
    /**
     * Collapse multiple whitespace characters to single spaces. Default. Matches browser behavior.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("Normalized") NORMALIZED,
    /** Preserve all whitespace exactly as it appears in the HTML. */
    @com.fasterxml.jackson.annotation.JsonProperty("Strict") STRICT;

    @com.fasterxml.jackson.annotation.JsonValue
    fun toWire(): String =
    when (this) {
        NORMALIZED -> "Normalized"
        STRICT -> "Strict"
    }

    companion object {
        @com.fasterxml.jackson.annotation.JsonCreator
        @JvmStatic
        fun fromWire(value: String): WhitespaceMode =
        when (value) {
            "Normalized",
            "normalized" -> NORMALIZED
            "Strict",
            "strict" -> STRICT
            else -> throw IllegalArgumentException("Unknown WhitespaceMode value: $value")
        }
    }
}
