# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8dea94481bd49cb01133074b75a8890f65b73e10cf3c4d9b2c19213e09a9f9be
# To regenerate: alef generate
# To verify freshness: alef verify
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
