# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
