# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aff1fb6a41198ba936446c1d39dc1abf10cc3a3e9adfd5d483552b6c011e752f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The html_to_markdown package is expected to be installed in the current environment.
