// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44701da9f40792f62b8369e11b7c807c8b4ffdef3e9bc4cfc774dd6045e07821
// To regenerate: alef generate
// To verify freshness: alef verify
// ignore_for_file: unused_local_variable, unused_element

import 'package:test/test.dart';
import 'package:h2m/h2m.dart';
import 'package:h2m/src/html_to_markdown_rs_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: structure

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

void main() {
  var _rustLibInitialized = false;

  setUpAll(() async {
    await RustLib.init();
    _rustLibInitialized = true;
  });

  tearDownAll(() async {
    if (_rustLibInitialized) {
      RustLib.dispose();
    }
  });

  test('Fenced code block produces Code node', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<p>Example code:</p><pre><code class="language-rust">fn main() { println!("Hello"); }</code></pre>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(2));
  });

  test('H1 > H2 > H3 creates three levels of heading nesting', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<h1>Top Level</h1><p>Top intro.</p><h2>Mid Level</h2><p>Mid content.</p><h3>Deep Level</h3><p>Deep content.</p>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(5));
  });

  test('H1 followed by H2 creates a nested group under the H1', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<h1>Chapter One</h1><p>Chapter intro.</p><h2>Section One</h2><p>Section content.</p>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(3));
  });

  test('Simple heading followed by paragraph produces Heading and Paragraph nodes', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<h1>Title</h1><p>A paragraph of text.</p>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(2));
  });

  test('Unordered list produces List and ListItem nodes', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<p>Items:</p><ul><li>Alpha</li><li>Beta</li><li>Gamma</li></ul>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(2));
  });

  test('Multiple headings create multiple Heading nodes with correct levels', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<h1>Main Title</h1><h2>Section One</h2><p>Section one content.</p><h2>Section Two</h2><p>Section two content.</p>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(4));
  });

  test('H1, H2, then another H1 creates two sibling top-level groups', () async {
    final options = await createConversionOptionsFromJson(json: '{"include_document_structure":true}');
    final result = await H2mBridge.convert('<h1>Chapter One</h1><h2>Section A</h2><p>Section A content.</p><h1>Chapter Two</h1><h2>Section B</h2><p>Section B content.</p>', options: options);
    expect(result.content?.toString(), isNotEmpty);
    expect(result.document?.nodes?.toString(), isNotEmpty);
    expect(result.document?.nodes.length, greaterThanOrEqualTo(4));
  });

}
