<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:871e4f8dbce03d8aa1b726a6e3dd4ba9eee521958cd9a5d53e11b3ca29db0c48
// To regenerate: alef generate
// To verify freshness: alef verify

declare(strict_types=1);


// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../crates/html-to-markdown-php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
