<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71adfc2ecb2d01d740d17e422205dfa69c729bb876fe48ab4a3a556d99178b83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

declare(strict_types=1);


// Load the e2e project autoloader (PHPUnit, test helpers).
require_once __DIR__ . '/vendor/autoload.php';

// Load the PHP binding package classes via its Composer autoloader.
// The package's autoloader is separate from the e2e project's autoloader
// since the php-ext type prevents direct composer path dependency.
$pkgAutoloader = __DIR__ . '/../../packages/php/vendor/autoload.php';
if (file_exists($pkgAutoloader)) {
    require_once $pkgAutoloader;
}
