// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4407723566747391e4ca23d69a5acd22c92c296b722ef970a3b6202435c9b2f5
// To regenerate: alef generate
// To verify freshness: alef verify

package e2e_test

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

func TestMain(m *testing.M) {
	_, filename, _, _ := runtime.Caller(0)
	dir := filepath.Dir(filename)

	// Change to the configured test-documents directory (if it exists) so that fixture
	// file paths like "pdf/fake_memo.pdf" resolve correctly when running go test
	// from e2e/go/. Repos without document fixtures skip chdir and run from e2e/go/.
	testDocumentsDir := filepath.Join(dir, "..", "..", "test_documents")
	if info, err := os.Stat(testDocumentsDir); err == nil && info.IsDir() {
		if err := os.Chdir(testDocumentsDir); err != nil {
			panic(err)
		}
	}

	os.Exit(m.Run())
}
