// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e598405c6a8978873ce2dbefd785f8e8e6883ece2c86dac6fa9532a93fbaffa3
// To regenerate: alef generate
// To verify freshness: alef verify

// E2e tests for category: smoke
package e2e_test

import (
	"strings"
	"testing"

	htmd "github.com/xberg-io/html-to-markdown/packages/go/v3"
)

func Test_SmokeEmptyString(t *testing.T) {
	// Empty string produces empty output
	result, err := htmd.Convert(``, nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var content string
	if result.Content != nil {
		content = string(*result.Content)
	}
	if string(content) != `` {
		t.Errorf("equals mismatch: got %v", content)
	}
}

func Test_SmokeSimpleHeading(t *testing.T) {
	// H1 heading converts to ATX markdown
	result, err := htmd.Convert(`<h1>Title</h1>`, nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if result.Content == nil || !strings.Contains(string(*result.Content), `# Title`) {
		t.Errorf("expected to contain %s", `# Title`)
	}
}

func Test_SmokeSimpleParagraph(t *testing.T) {
	// Simple paragraph converts correctly
	result, err := htmd.Convert(`<p>Hello World</p>`, nil)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	var content string
	if result.Content != nil {
		content = string(*result.Content)
	}
	if string(content) != `Hello World` {
		t.Errorf("equals mismatch: got %v", content)
	}
	if len(content) == 0 {
		t.Errorf("expected non-empty value")
	}
}
